
solution {
    puzzle = "P101"
    name = "B X S 6T"
    arm(ARM1) {
        number = 1
        position = 2 to -2
        rotation = 2
        size = 1
    }
    arm(ARM1) {
        number = 2
        position = 0 to -3
        rotation = 0
        size = 1
    }
    arm(ARM1) {
        number = 3
        position = -3 to 2
        rotation = 5
        size = 2
    }
    arm(ARM1) {
        number = 4
        position = -2 to 1
        rotation = 5
        size = 2
    }
    arm(ARM1) {
        number = 5
        position = -4 to 1
        rotation = -1
        size = 2
    }
    arm(PISTON) {
        number = 6
        position = -2 to -3
        rotation = 1
        size = 2
    }
    arm(ARM1) {
        number = 7
        position = -1 to -3
        rotation = 1
        size = 1
    }
    glyph(BONDER) {
        position = -3 to -2
        rotation = 0
    }
    glyph(BONDER) {
        position = -5 to -2
        rotation = 1
    }
    glyph(UNBONDER) {
        position = -2 to -1
        rotation = 0
    }
    glyph(CALCIFICATION) {
        position = -4 to -2
        rotation = 0
    }
    glyph(PROJECTION) {
        position = 0 to -1
        rotation = -2
    }
    glyph(PURIFICATION) {
        position = 2 to -3
        rotation = 2
    }
    glyph(EQUILIBRIUM) {
        position = -5 to -3
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -6 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -5 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -4 to -1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -3 to -1
        rotation = 0
    }
    io(INFINITE) {
        index = 0
        position = -18 to -1
        rotation = 0
    }
    io(INPUT) {
        index = 0
        position = -1 to 0
        rotation = 3
    }
    io(INPUT) {
        index = 1
        position = 1 to -1
        rotation = 0
    }
    track {
        position = -4 to 0
        positions = listOf(0 to 1, 0 to 0, 1 to 0)
    }
    track {
        position = -4 to -3
        positions = listOf(0 to 0, 1 to 0, 2 to 0, 3 to 0, 3 to 1)
    }
    track {
        position = -1 to 1
        positions = listOf(-1 to 0, -2 to 0, -2 to 1)
    }
    tape {
        parallel(
        {
            sequence(6) {
                wait(9)
                grab()
                retract()
                drop()
                extend()
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                back()
                grab()
                forward()
                back()
                extend()
                back()
                drop()
                rotateClockwise()
                forward()
                forward()
                grab()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                back()
                back()
                extend()
                drop()
                rotateClockwise()
                rotateClockwise()
                forward()
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                wait(1)
                grab()
                back()
                extend()
                wait(1)
                back()
                drop()
                rotateClockwise()
                forward()
                forward()
                grab()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                back()
                back()
                extend()
                drop()
                rotateClockwise()
                rotateClockwise()
                forward()
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                wait(1)
                grab()
                back()
                extend()
                wait(1)
                back()
                drop()
                rotateClockwise()
                forward()
                forward()
                grab()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                back()
                back()
                extend()
                drop()
                rotateClockwise()
                rotateClockwise()
                forward()
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                wait(1)
                grab()
                back()
                extend()
                wait(1)
                back()
                drop()
                rotateClockwise()
                forward()
                forward()
                grab()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                back()
                back()
                extend()
                drop()
                rotateClockwise()
                rotateClockwise()
                forward()
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                wait(1)
                grab()
                back()
                extend()
                wait(1)
                back()
                drop()
                rotateClockwise()
                forward()
                forward()
                grab()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                back()
                back()
                extend()
                drop()
                rotateClockwise()
                rotateClockwise()
                forward()
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                wait(1)
                grab()
                back()
                extend()
                wait(1)
                back()
                drop()
                rotateClockwise()
                forward()
                forward()
                grab()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                back()
                back()
                extend()
                extend()
                retract()
                reset()
            }
        }
        , 
        {
            sequence(2) {
                wait(9)
                grab()
                rotateCounterClockwise()
                wait(3)
                rotateCounterClockwise()
                reset()
                wait(5)
                grab()
                rotateCounterClockwise()
                wait(3)
                rotateCounterClockwise()
                reset()
                wait(3)
                grab()
                rotateCounterClockwise()
                wait(5)
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                wait(9)
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                wait(5)
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                wait(9)
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                wait(5)
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                wait(9)
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                wait(5)
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                wait(9)
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                wait(5)
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                wait(9)
                rotateCounterClockwise()
                reset()
            }
        }
        , 
        {
            sequence(7) {
                wait(15)
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                drop()
                wait(2)
                forward()
                grab()
                back()
                drop()
                rotateClockwise()
                wait(1)
                grab()
                rotateCounterClockwise()
                drop()
                forward()
                grab()
                back()
                back()
                drop()
                rotateClockwise()
                forward()
                wait(2)
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                drop()
                wait(3)
                forward()
                grab()
                back()
                drop()
                rotateClockwise()
                wait(1)
                grab()
                rotateCounterClockwise()
                drop()
                forward()
                grab()
                back()
                back()
                drop()
                rotateClockwise()
                forward()
                wait(2)
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                drop()
                wait(3)
                forward()
                grab()
                back()
                drop()
                rotateClockwise()
                wait(1)
                grab()
                rotateCounterClockwise()
                drop()
                forward()
                grab()
                back()
                back()
                drop()
                rotateClockwise()
                forward()
                wait(2)
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                drop()
                wait(3)
                forward()
                grab()
                back()
                drop()
                rotateClockwise()
                wait(1)
                grab()
                rotateCounterClockwise()
                drop()
                forward()
                grab()
                back()
                back()
                drop()
                rotateClockwise()
                forward()
                wait(2)
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                drop()
                wait(3)
                forward()
                grab()
                back()
                drop()
                rotateClockwise()
                wait(1)
                grab()
                rotateCounterClockwise()
                drop()
                forward()
                grab()
                back()
                back()
                drop()
                rotateClockwise()
                forward()
                wait(2)
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                drop()
                wait(3)
                forward()
                grab()
                back()
                drop()
                rotateClockwise()
                wait(1)
                grab()
                rotateCounterClockwise()
                drop()
                forward()
                reset()
            }
        }
        , 
        {
            sequence(3) {
                wait(4)
                grab()
                back()
                back()
                drop()
                back()
                wait(2)
                grab()
                back()
                back()
                drop()
                wait(1)
                back()
                wait(4)
                grab()
                back()
                back()
                drop()
                back()
                wait(4)
                grab()
                back()
                back()
                drop()
                back()
                grab()
                back()
                back()
                drop()
                wait(6)
                back()
                grab()
                wait(1)
                back()
                back()
                drop()
                back()
                wait(4)
                grab()
                back()
                back()
                drop()
                back()
                grab()
                back()
                back()
                drop()
                wait(6)
                back()
                grab()
                wait(1)
                back()
                back()
                drop()
                back()
                wait(4)
                grab()
                back()
                back()
                drop()
                back()
                grab()
                back()
                back()
                drop()
                wait(6)
                back()
                grab()
                wait(1)
                back()
                back()
                drop()
                back()
                wait(4)
                grab()
                back()
                back()
                drop()
                back()
                grab()
                back()
                back()
                drop()
                wait(6)
                back()
                grab()
                wait(1)
                back()
                back()
                drop()
                back()
                wait(4)
                grab()
                back()
                back()
                drop()
                back()
                grab()
                back()
                back()
                drop()
                wait(6)
                back()
                grab()
                wait(1)
                back()
                back()
                reset()
            }
        }
        , 
        {
            sequence(4) {
                wait(6)
                back()
                grab()
                back()
                wait(2)
                back()
                drop()
                back()
                wait(1)
                grab()
                back()
                back()
                drop()
                wait(3)
                back()
                grab()
                back()
                back()
                drop()
                wait(4)
                back()
                grab()
                back()
                back()
                drop()
                back()
                wait(7)
                grab()
                back()
                back()
                wait(1)
                drop()
                back()
                grab()
                back()
                back()
                drop()
                wait(3)
                back()
                grab()
                back()
                back()
                drop()
                back()
                wait(7)
                grab()
                back()
                back()
                wait(1)
                drop()
                back()
                grab()
                back()
                back()
                drop()
                wait(3)
                back()
                grab()
                back()
                back()
                drop()
                back()
                wait(7)
                grab()
                back()
                back()
                wait(1)
                drop()
                back()
                grab()
                back()
                back()
                drop()
                wait(3)
                back()
                grab()
                back()
                back()
                drop()
                back()
                wait(7)
                grab()
                back()
                back()
                wait(1)
                drop()
                back()
                grab()
                back()
                back()
                drop()
                wait(3)
                back()
                grab()
                back()
                back()
                drop()
                back()
                wait(7)
                grab()
                back()
                back()
                wait(1)
                drop()
                back()
                grab()
                back()
                back()
                reset()
            }
        }
        , 
        {
            sequence(1) {
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                reset()
                wait(1)
                repeat()
                wait(10)
                repeat()
                wait(9)
                repeat()
                wait(10)
                repeat()
                wait(9)
                repeat()
                wait(10)
                repeat()
                wait(9)
                repeat()
                wait(10)
                repeat()
                wait(16)
                repeat()
                wait(10)
                repeat()
                wait(13)
                repeat()
            }
        }
        , 
        {
            sequence(5) {
                wait(7)
                grab()
                back()
                rotateClockwise()
                wait(1)
                pivotCounterClockwise()
                back()
                reset()
                wait(3)
                grab()
                back()
                wait(2)
                rotateClockwise()
                wait(3)
                back()
                wait(2)
                pivotClockwise()
                pivotClockwise()
                wait(1)
                forward()
                reset()
                wait(2)
                grab()
                forward()
                pivotClockwise()
                rotateClockwise()
                wait(4)
                forward()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                back()
                wait(1)
                back()
                wait(1)
                pivotClockwise()
                pivotClockwise()
                wait(2)
                forward()
                reset()
                wait(2)
                grab()
                forward()
                pivotClockwise()
                rotateClockwise()
                wait(4)
                forward()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                back()
                wait(1)
                back()
                wait(1)
                pivotClockwise()
                pivotClockwise()
                wait(2)
                forward()
                reset()
                wait(2)
                grab()
                forward()
                pivotClockwise()
                rotateClockwise()
                wait(4)
                forward()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                back()
                wait(1)
                back()
                wait(1)
                pivotClockwise()
                pivotClockwise()
                wait(2)
                forward()
                reset()
                wait(2)
                grab()
                forward()
                pivotClockwise()
                rotateClockwise()
                wait(4)
                forward()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                back()
                wait(1)
                back()
                wait(1)
                pivotClockwise()
                pivotClockwise()
                wait(2)
                forward()
                reset()
                wait(2)
                grab()
                forward()
                pivotClockwise()
                rotateClockwise()
                wait(4)
                forward()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                back()
                wait(1)
                back()
                wait(1)
                pivotClockwise()
                pivotClockwise()
                wait(2)
                forward()
                reset()
            }
        }
        )
    }
}
