
solution {
    puzzle = "P068"
    name = "B AA"
    arm(PISTON) {
        number = 1
        position = -2 to 1
        rotation = -11
        size = 3
    }
    arm(PISTON) {
        number = 2
        position = 1 to 2
        rotation = -10
        size = 2
    }
    glyph(MULTI_BONDER) {
        position = -1 to 2
        rotation = -16
    }
    glyph(UNBONDER) {
        position = 0 to 3
        rotation = -15
    }
    glyph(PURIFICATION) {
        position = 1 to 0
        rotation = -17
    }
    glyph(EQUILIBRIUM) {
        position = -4 to 5
        rotation = 0
    }
    io(INPUT) {
        index = 0
        position = -2 to 5
        rotation = -10
    }
    io(OUTPUT) {
        index = 0
        position = -4 to 3
        rotation = -15
    }
    track {
        position = -1 to 0
        positions = listOf(-1 to 0, -1 to 1)
    }
    tape {
        parallel(
        {
            sequence(2) {
                wait(2)
                grab()
                pivotCounterClockwise()
                reset()
                retract()
                grab()
                extend()
                extend()
                reset()
                wait(1)
                grab()
                retract()
                pivotClockwise()
                wait(2)
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                wait(2)
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                reset()
                wait(3)
                grab()
                retract()
                pivotClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                reset()
                wait(4)
                grab()
                retract()
                pivotClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                pivotCounterClockwise()
                extend()
                drop()
                rotateClockwise()
                grab()
                retract()
                retract()
                rotateCounterClockwise()
                extend()
                reset()
                wait(6)
                grab()
                retract()
                wait(2)
                extend()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                retract()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                wait(1)
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                pivotClockwise()
                rotateCounterClockwise()
                wait(2)
                extend()
                drop()
                rotateClockwise()
                grab()
                pivotCounterClockwise()
                drop()
                retract()
                grab()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                drop()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                extend()
                grab()
                retract()
                reset()
                wait(1)
                grab()
                retract()
                pivotClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                rotateCounterClockwise()
                retract()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                wait(7)
                grab()
                pivotClockwise()
                extend()
                drop()
                rotateClockwise()
                grab()
                retract()
                retract()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                drop()
                rotateClockwise()
                rotateClockwise()
                wait(2)
                grab()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                wait(1)
                grab()
                rotateClockwise()
                extend()
                extend()
                reset()
            }
        }
        , 
        {
            sequence(1) {
                grab()
                retract()
                reset()
                wait(2)
                grab()
                pivotClockwise()
                wait(1)
                pivotCounterClockwise()
                reset()
                retract()
                wait(3)
                grab()
                retract()
                rotateCounterClockwise()
                extend()
                pivotClockwise()
                rotateClockwise()
                extend()
                reset()
                rotateClockwise()
                grab()
                retract()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                reset()
                wait(4)
                grab()
                retract()
                pivotCounterClockwise()
                reset()
                wait(1)
                grab()
                pivotCounterClockwise()
                drop()
                rotateClockwise()
                grab()
                retract()
                retract()
                drop()
                rotateCounterClockwise()
                wait(5)
                grab()
                extend()
                drop()
                retract()
                grab()
                extend()
                pivotCounterClockwise()
                pivotCounterClockwise()
                wait(2)
                rotateCounterClockwise()
                pivotCounterClockwise()
                extend()
                reset()
                wait(1)
                grab()
                retract()
                reset()
                wait(1)
                grab()
                pivotClockwise()
                drop()
                retract()
                retract()
                rotateCounterClockwise()
                back()
                grab()
                extend()
                drop()
                rotateClockwise()
                wait(3)
                grab()
                pivotClockwise()
                forward()
                reset()
                wait(1)
                rotateClockwise()
                grab()
                retract()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                reset()
                wait(2)
                rotateClockwise()
                grab()
                retract()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                drop()
                rotateClockwise()
                extend()
                wait(2)
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                extend()
                reset()
                retract()
                rotateClockwise()
                grab()
                retract()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                back()
                extend()
                wait(5)
                grab()
                forward()
                retract()
                rotateClockwise()
                rotateClockwise()
                extend()
                extend()
                reset()
                wait(1)
                rotateCounterClockwise()
                grab()
                retract()
                pivotClockwise()
                rotateClockwise()
                back()
                drop()
                wait(4)
                grab()
                forward()
                pivotCounterClockwise()
                extend()
                reset()
                retract()
                retract()
                rotateCounterClockwise()
                back()
                grab()
                forward()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                back()
                pivotClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                wait(1)
                reset()
            }
        }
        )
    }
}
