
solution {
    puzzle = "w2450512434"
    name = "OVERLAP AC 6T"
    arm(PISTON) {
        number = 1
        position = 1 to 2
        rotation = -3
        size = 2
    }
    glyph(BONDER) {
        position = -2 to 2
        rotation = 0
    }
    glyph(BONDER) {
        position = -2 to 1
        rotation = 0
    }
    glyph(BONDER) {
        position = 0 to 1
        rotation = 1
    }
    glyph(UNBONDER) {
        position = -1 to 1
        rotation = 1
    }
    glyph(UNBONDER) {
        position = -1 to 1
        rotation = 0
    }
    glyph(UNBONDER) {
        position = -1 to 2
        rotation = -1
    }
    glyph(UNBONDER) {
        position = -1 to 2
        rotation = 0
    }
    glyph(UNBONDER) {
        position = 1 to 0
        rotation = 2
    }
    glyph(UNBONDER) {
        position = 1 to 2
        rotation = 3
    }
    glyph(PURIFICATION) {
        position = 1 to 1
        rotation = -4
    }
    glyph(PURIFICATION) {
        position = 1 to 0
        rotation = 1
    }
    glyph(EQUILIBRIUM) {
        position = -12 to 1
        rotation = 0
    }
    io(INPUT) {
        index = 0
        position = 0 to 2
        rotation = -2
    }
    io(INFINITE) {
        index = 0
        position = -12 to 1
        rotation = 0
    }
    io(INFINITE) {
        index = 1
        position = -12 to 2
        rotation = 0
    }
    track {
        position = 1 to 2
        positions = listOf(0 to 0, 0 to -1, -1 to -1, -1 to 0)
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                extend()
                drop()
                retract()
                retract()
                forward()
                grab()
                pivotCounterClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                forward()
                grab()
                back()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                grab()
                forward()
                extend()
                drop()
                back()
                back()
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                extend()
                drop()
                retract()
                grab()
                extend()
                drop()
                retract()
                retract()
                grab()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                drop()
                forward()
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                forward()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                back()
                rotateCounterClockwise()
                forward()
                extend()
                drop()
                retract()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                grab()
                extend()
                drop()
                retract()
                forward()
                forward()
                grab()
                back()
                extend()
                extend()
                drop()
                reset()
                grab()
                extend()
                drop()
                retract()
                retract()
                forward()
                grab()
                pivotCounterClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                forward()
                extend()
                grab()
                back()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                forward()
                extend()
                drop()
                back()
                back()
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                extend()
                drop()
                retract()
                grab()
                extend()
                drop()
                retract()
                retract()
                grab()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                drop()
                forward()
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                forward()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                back()
                rotateCounterClockwise()
                forward()
                extend()
                drop()
                retract()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                grab()
                extend()
                drop()
                retract()
                forward()
                forward()
                grab()
                back()
                extend()
                extend()
                drop()
                reset()
                grab()
                extend()
                drop()
                retract()
                retract()
                forward()
                grab()
                pivotCounterClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                forward()
                extend()
                grab()
                back()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                forward()
                extend()
                drop()
                back()
                back()
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                extend()
                drop()
                retract()
                grab()
                extend()
                drop()
                retract()
                retract()
                grab()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                drop()
                forward()
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                forward()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                back()
                rotateCounterClockwise()
                forward()
                extend()
                drop()
                retract()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                grab()
                extend()
                drop()
                retract()
                forward()
                forward()
                grab()
                back()
                extend()
                extend()
                drop()
                reset()
                grab()
                extend()
                drop()
                retract()
                retract()
                forward()
                grab()
                pivotCounterClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                forward()
                extend()
                grab()
                back()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                forward()
                extend()
                drop()
                back()
                back()
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                extend()
                drop()
                retract()
                grab()
                extend()
                drop()
                retract()
                retract()
                grab()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                drop()
                forward()
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                forward()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                back()
                rotateCounterClockwise()
                forward()
                drop()
                forward()
                grab()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                rotateClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                pivotCounterClockwise()
                drop()
                back()
                back()
                rotateCounterClockwise()
                extend()
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                reset()
            }
        }
        )
    }
}
