
solution {
    puzzle = "P054"
    name = "H3 6T"
    arm(VAN_BERLOS_WHEEL) {
        number = 1
        position = -4 to 0
        rotation = 2
        size = 1
    }
    arm(PISTON) {
        number = 2
        position = 6 to 1
        rotation = -1
        size = 2
    }
    arm(PISTON) {
        number = 3
        position = 5 to 0
        rotation = 0
        size = 2
    }
    arm(PISTON) {
        number = 4
        position = 11 to 1
        rotation = 3
        size = 3
    }
    arm(ARM1) {
        number = 5
        position = 12 to 1
        rotation = 3
        size = 3
    }
    arm(ARM1) {
        number = 6
        position = -1 to 1
        rotation = 3
        size = 1
    }
    arm(ARM1) {
        number = 7
        position = 0 to 1
        rotation = 3
        size = 1
    }
    arm(ARM1) {
        number = 8
        position = 1 to 1
        rotation = 3
        size = 1
    }
    arm(ARM1) {
        number = 9
        position = 2 to 1
        rotation = 3
        size = 1
    }
    arm(ARM1) {
        number = 10
        position = 3 to 1
        rotation = 3
        size = 1
    }
    arm(ARM1) {
        number = 11
        position = 4 to 1
        rotation = 3
        size = 1
    }
    arm(ARM1) {
        number = 12
        position = 5 to 1
        rotation = 3
        size = 1
    }
    arm(ARM1) {
        number = 13
        position = 6 to 0
        rotation = 9
        size = 1
    }
    arm(ARM1) {
        number = 14
        position = 6 to -1
        rotation = 9
        size = 1
    }
    arm(ARM1) {
        number = 15
        position = 5 to -1
        rotation = 9
        size = 1
    }
    arm(ARM1) {
        number = 16
        position = 4 to -1
        rotation = 9
        size = 1
    }
    arm(ARM1) {
        number = 17
        position = 3 to -1
        rotation = 9
        size = 1
    }
    glyph(BONDER) {
        position = 7 to 0
        rotation = 0
    }
    glyph(BONDER) {
        position = 12 to 0
        rotation = -1
    }
    glyph(DUPLICATION) {
        position = -3 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 9 to -1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 7 to -1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 7 to 1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 4 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 3 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 2 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 1 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -1 to -1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 12 to -1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 8 to 1
        rotation = 0
    }
    io(INPUT) {
        index = 0
        position = 8 to -1
        rotation = 0
    }
    io(OUTPUT) {
        index = 0
        position = 10 to 0
        rotation = 2
    }
    io(INPUT) {
        index = 1
        position = -2 to 1
        rotation = 0
    }
    track {
        position = 0 to -1
        positions = listOf(0 to 0, -1 to 1, -1 to 2, 0 to 2, 1 to 2, 2 to 2, 3 to 2, 4 to 2, 5 to 2, 6 to 1, 6 to 0, 5 to 0, 4 to 0, 3 to 0, 2 to 0, 1 to 0)
    }
    track {
        position = 16 to -1
        positions = listOf(0 to 0, -1 to 0, -2 to 0, -3 to 1, -3 to 2, -4 to 2, -5 to 2)
    }
    tape {
        parallel(
        {
            sequence(3) {
                wait(11)
                grab()
                extend()
                pivotClockwise()
                wait(1)
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                reset()
                wait(2)
                grab()
                extend()
                pivotClockwise()
                wait(1)
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                wait(1)
                pivotClockwise()
                reset()
                wait(2)
                grab()
                extend()
                pivotClockwise()
                wait(2)
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                reset()
                wait(2)
                grab()
                extend()
                pivotClockwise()
                wait(1)
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                wait(1)
                pivotClockwise()
                reset()
                wait(2)
                grab()
                extend()
                pivotClockwise()
                wait(2)
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                reset()
                wait(2)
                grab()
                extend()
                pivotClockwise()
                wait(1)
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                wait(1)
                pivotClockwise()
                pivotClockwise()
                reset()
            }
        }
        , 
        {
            sequence(2) {
                wait(5)
                grab()
                rotateCounterClockwise()
                reset()
                wait(1)
                grab()
                retract()
                reset()
                wait(2)
                grab()
                retract()
                reset()
                wait(7)
                grab()
                retract()
                reset()
                wait(1)
                grab()
                retract()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                reset()
                wait(1)
                grab()
                retract()
                reset()
                wait(7)
                grab()
                retract()
                reset()
                wait(1)
                grab()
                retract()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                reset()
                wait(1)
                grab()
                retract()
                reset()
                wait(7)
                grab()
                retract()
                reset()
                wait(1)
                grab()
                retract()
                reset()
            }
        }
        , 
        {
            sequence(6) {
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                wait(2)
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                wait(1)
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                grab()
                back()
                wait(2)
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                wait(1)
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                reset()
            }
        }
        , 
        {
            sequence(4) {
                wait(13)
                grab()
                retract()
                reset()
                wait(2)
                grab()
                retract()
                pivotCounterClockwise()
                back()
                back()
                forward()
                forward()
                reset()
                wait(4)
                grab()
                retract()
                retract()
                reset()
                wait(2)
                repeat()
                wait(22)
                grab()
                retract()
                reset()
                wait(2)
                grab()
                retract()
                pivotCounterClockwise()
                back()
                back()
                forward()
                forward()
                reset()
                wait(5)
                grab()
                retract()
                retract()
                reset()
            }
        }
        , 
        {
            sequence(7) {
                wait(1)
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                grab()
                back()
                back()
                back()
                wait(2)
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                wait(1)
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                wait(2)
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                wait(1)
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
            }
        }
        , 
        {
            sequence(8) {
                wait(2)
                back()
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                grab()
                back()
                wait(2)
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                wait(1)
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                wait(2)
                back()
                back()
                grab()
                back()
                back()
                back()
                wait(1)
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                reset()
            }
        }
        , 
        {
            sequence(9) {
                wait(3)
                back()
                back()
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                wait(2)
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                wait(1)
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                wait(2)
                rotateClockwise()
                back()
                back()
                back()
                grab()
                back()
                wait(1)
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                back()
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(10) {
                wait(4)
                back()
                back()
                back()
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                wait(2)
                back()
                back()
                grab()
                back()
                back()
                back()
                wait(1)
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                wait(2)
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                wait(1)
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                back()
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(11) {
                wait(5)
                back()
                back()
                back()
                back()
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                wait(2)
                rotateClockwise()
                back()
                back()
                back()
                grab()
                back()
                wait(1)
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                wait(2)
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                wait(1)
                back()
                back()
                wait(1)
                back()
                back()
                back()
                back()
                wait(1)
                back()
                wait(1)
                back()
                wait(1)
                back()
                back()
                reset()
            }
        }
        , 
        {
            sequence(12) {
                wait(5)
                back()
                back()
                wait(1)
                back()
                back()
                back()
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                wait(2)
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                wait(1)
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                wait(2)
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                wait(1)
                rotateClockwise()
                back()
                back()
                back()
                wait(1)
                back()
                back()
                back()
                back()
                wait(1)
                back()
                wait(1)
                back()
                wait(1)
                reset()
            }
        }
        , 
        {
            sequence(13) {
                wait(6)
                back()
                wait(1)
                back()
                back()
                back()
                back()
                back()
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                back()
                back()
                wait(2)
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                wait(1)
                back()
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                wait(2)
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                wait(1)
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                wait(1)
                back()
                back()
                back()
                back()
                wait(1)
                back()
                wait(1)
                reset()
            }
        }
        , 
        {
            sequence(14) {
                wait(6)
                back()
                wait(1)
                back()
                back()
                back()
                back()
                back()
                back()
                wait(1)
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                wait(2)
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                wait(1)
                rotateClockwise()
                back()
                back()
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                wait(2)
                back()
                back()
                back()
                drop()
                back()
                back()
                wait(1)
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                wait(1)
                back()
                back()
                back()
                back()
                wait(1)
                reset()
            }
        }
        , 
        {
            sequence(15) {
                wait(6)
                back()
                wait(1)
                back()
                back()
                back()
                back()
                back()
                back()
                wait(1)
                back()
                wait(1)
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                wait(2)
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                wait(1)
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                wait(2)
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                wait(1)
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                wait(1)
                back()
                back()
                back()
                reset()
            }
        }
        , 
        {
            sequence(16) {
                wait(6)
                back()
                wait(1)
                back()
                back()
                back()
                back()
                back()
                back()
                wait(1)
                back()
                wait(1)
                back()
                wait(1)
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                wait(2)
                back()
                back()
                back()
                drop()
                back()
                back()
                wait(1)
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                wait(2)
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                wait(1)
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                wait(1)
                back()
                reset()
            }
        }
        , 
        {
            sequence(17) {
                wait(6)
                back()
                wait(1)
                back()
                back()
                back()
                back()
                back()
                back()
                wait(1)
                back()
                wait(1)
                back()
                wait(1)
                back()
                wait(1)
                back()
                grab()
                back()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                wait(2)
                back()
                rotateClockwise()
                back()
                back()
                back()
                drop()
                wait(1)
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                grab()
                back()
                back()
                back()
                wait(2)
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                wait(1)
                back()
                back()
                back()
                drop()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                reset()
            }
        }
        , 
        {
            sequence(5) {
                wait(15)
                grab()
                back()
                back()
                back()
                back()
                wait(2)
                back()
                drop()
                forward()
                forward()
                forward()
                wait(6)
                grab()
                pivotClockwise()
                reset()
                wait(2)
                repeat()
                wait(22)
                grab()
                back()
                back()
                back()
                back()
                wait(2)
                back()
                reset()
            }
        }
        , 
        {
            sequence(1) {
                wait(3)
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                wait(1)
                rotateClockwise()
                wait(1)
                rotateClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateClockwise()
                wait(1)
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                wait(1)
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateClockwise()
                wait(2)
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                wait(1)
                rotateClockwise()
                wait(1)
                rotateClockwise()
                wait(2)
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateClockwise()
                wait(1)
                rotateClockwise()
                rotateClockwise()
                wait(1)
                rotateClockwise()
                wait(1)
                rotateCounterClockwise()
                rotateCounterClockwise()
                wait(1)
                rotateClockwise()
                wait(1)
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                wait(1)
                rotateClockwise()
                wait(1)
                rotateClockwise()
                wait(2)
                rotateCounterClockwise()
                rotateCounterClockwise()
                wait(1)
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                wait(2)
                reset()
            }
        }
        )
    }
}
