
solution {
    puzzle = "w2501727889"
    name = "NEW SOLUTION 1"
    arm(PISTON) {
        number = 1
        position = 1 to 0
        rotation = 4
        size = 2
    }
    arm(PISTON) {
        number = 2
        position = 5 to -1
        rotation = 3
        size = 3
    }
    arm(PISTON) {
        number = 3
        position = 9 to 0
        rotation = 3
        size = 3
    }
    arm(PISTON) {
        number = 4
        position = 13 to 0
        rotation = 3
        size = 3
    }
    arm(PISTON) {
        number = 5
        position = 17 to 0
        rotation = 3
        size = 3
    }
    arm(PISTON) {
        number = 6
        position = 21 to 0
        rotation = 3
        size = 3
    }
    glyph(BONDER) {
        position = 0 to 0
        rotation = 1
    }
    glyph(BONDER) {
        position = 0 to 1
        rotation = 0
    }
    glyph(BONDER) {
        position = 2 to 0
        rotation = 0
    }
    glyph(BONDER) {
        position = 1 to -1
        rotation = 2
    }
    glyph(BONDER) {
        position = 7 to 0
        rotation = -1
    }
    glyph(BONDER) {
        position = 5 to 1
        rotation = -1
    }
    glyph(BONDER) {
        position = 4 to 1
        rotation = 0
    }
    glyph(BONDER) {
        position = 6 to 0
        rotation = 0
    }
    glyph(BONDER) {
        position = 4 to 0
        rotation = 1
    }
    glyph(BONDER) {
        position = 11 to 0
        rotation = -1
    }
    glyph(BONDER) {
        position = 9 to 1
        rotation = -1
    }
    glyph(BONDER) {
        position = 8 to 0
        rotation = 1
    }
    glyph(BONDER) {
        position = 8 to 1
        rotation = 0
    }
    glyph(BONDER) {
        position = 10 to 0
        rotation = 0
    }
    glyph(BONDER) {
        position = 9 to -1
        rotation = 2
    }
    glyph(BONDER) {
        position = 15 to 0
        rotation = -1
    }
    glyph(BONDER) {
        position = 13 to 1
        rotation = -1
    }
    glyph(BONDER) {
        position = 12 to 0
        rotation = 1
    }
    glyph(BONDER) {
        position = 12 to 1
        rotation = 0
    }
    glyph(BONDER) {
        position = 14 to 0
        rotation = 0
    }
    glyph(BONDER) {
        position = 13 to -1
        rotation = 2
    }
    glyph(BONDER) {
        position = 19 to 0
        rotation = -1
    }
    glyph(BONDER) {
        position = 17 to 1
        rotation = -1
    }
    glyph(BONDER) {
        position = 16 to 0
        rotation = 1
    }
    glyph(BONDER) {
        position = 16 to 1
        rotation = 0
    }
    glyph(BONDER) {
        position = 18 to 0
        rotation = 0
    }
    glyph(BONDER) {
        position = 17 to -1
        rotation = 2
    }
    glyph(BONDER) {
        position = 21 to 1
        rotation = -1
    }
    glyph(BONDER) {
        position = 20 to 0
        rotation = 1
    }
    glyph(BONDER) {
        position = 20 to 1
        rotation = 0
    }
    glyph(BONDER) {
        position = 22 to 0
        rotation = 0
    }
    glyph(BONDER) {
        position = 21 to -1
        rotation = 2
    }
    glyph(BONDER) {
        position = 1 to 1
        rotation = -1
    }
    glyph(BONDER) {
        position = 8 to 0
        rotation = -2
    }
    glyph(BONDER) {
        position = 12 to 0
        rotation = -2
    }
    glyph(BONDER) {
        position = 16 to 0
        rotation = -2
    }
    glyph(BONDER) {
        position = 20 to 0
        rotation = -2
    }
    glyph(BONDER) {
        position = 4 to -1
        rotation = 2
    }
    glyph(BONDER) {
        position = 4 to -1
        rotation = 1
    }
    glyph(CALCIFICATION) {
        position = 2 to -1
        rotation = 0
    }
    glyph(ANIMISMUS) {
        position = 3 to -1
        rotation = 3
    }
    io(INPUT) {
        index = 0
        position = -1 to 0
        rotation = 0
    }
    io(INFINITE) {
        index = 0
        position = 0 to 0
        rotation = 0
    }
    io(INPUT) {
        index = 1
        position = 1 to -2
        rotation = 0
    }
    io(OUTPUT) {
        index = 1
        position = 3 to -2
        rotation = 0
    }
    track {
        position = 10 to -1
        positions = listOf(0 to 0, -1 to 1)
    }
    track {
        position = 14 to -1
        positions = listOf(0 to 0, -1 to 1)
    }
    track {
        position = 18 to -1
        positions = listOf(0 to 0, -1 to 1)
    }
    track {
        position = 22 to -1
        positions = listOf(0 to 0, -1 to 1)
    }
    track {
        position = 1 to 0
        positions = listOf(0 to 0, 1 to -1)
    }
    track {
        position = 5 to 0
        positions = listOf(0 to 0, 0 to -1)
    }
    tape {
        parallel(
        {
            sequence(4) {
                wait(26)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(9)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(13)
                repeat()
                wait(14)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(6)
                grab()
                retract()
                retract()
                rotateClockwise()
                reset()
                wait(7)
                grab()
                retract()
                back()
                retract()
                reset()
                wait(7)
                grab()
                retract()
                retract()
                reset()
                wait(8)
                grab()
                retract()
                back()
                reset()
                wait(8)
                grab()
                retract()
            }
        }
        , 
        {
            sequence(5) {
                wait(32)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(9)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(13)
                repeat()
                wait(14)
                repeat()
                wait(11)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(6)
                grab()
                retract()
                retract()
                rotateClockwise()
                reset()
                wait(7)
                grab()
                retract()
                back()
                retract()
                reset()
                wait(7)
                grab()
                retract()
                retract()
                reset()
                wait(8)
                grab()
                retract()
                back()
                reset()
                wait(8)
                grab()
                retract()
            }
        }
        , 
        {
            sequence(6) {
                wait(38)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                drop()
                retract()
                reset()
                wait(6)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                pivotClockwise()
                drop()
                retract()
                reset()
                wait(4)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(5)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(4)
                grab()
                retract()
                retract()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                extend()
                wait(3)
                grab()
                retract()
                back()
                retract()
                drop()
                forward()
                extend()
                extend()
                wait(4)
                grab()
                retract()
                retract()
                reset()
                wait(8)
                grab()
                retract()
                back()
                reset()
                wait(10)
                grab()
                retract()
            }
        }
        , 
        {
            sequence(3) {
                wait(20)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(9)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(13)
                repeat()
                wait(14)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(11)
                repeat()
                wait(12)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(6)
                grab()
                retract()
                retract()
                rotateClockwise()
                reset()
                wait(7)
                grab()
                retract()
                back()
                retract()
                reset()
                wait(7)
                grab()
                retract()
                retract()
                reset()
                wait(8)
                grab()
                retract()
                back()
                reset()
                wait(8)
                grab()
                retract()
            }
        }
        , 
        {
            sequence(2) {
                wait(9)
                grab()
                retract()
                drop()
                back()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                wait(4)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                extend()
                extend()
                grab()
                retract()
                drop()
                back()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                wait(2)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                wait(3)
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                wait(1)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                forward()
                retract()
                drop()
                back()
                extend()
                extend()
                wait(1)
                grab()
                retract()
                retract()
                drop()
                extend()
                extend()
                wait(12)
                grab()
                retract()
                wait(14)
                pivotCounterClockwise()
                pivotCounterClockwise()
            }
        }
        , 
        {
            sequence(1) {
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                drop()
                back()
                reset()
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                extend()
                drop()
                retract()
                retract()
                reset()
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                retract()
                wait(2)
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                drop()
                back()
                reset()
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                wait(2)
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                wait(2)
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                drop()
                back()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                drop()
                back()
                reset()
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                drop()
                back()
                reset()
                wait(2)
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                drop()
                back()
                reset()
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                drop()
                back()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                drop()
                back()
                reset()
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                wait(1)
                rotateClockwise()
                rotateClockwise()
                extend()
                extend()
                drop()
                retract()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                drop()
                back()
                reset()
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                drop()
                back()
                reset()
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                reset()
                wait(2)
                grab()
                retract()
                wait(13)
                extendTape()
            }
        }
        )
    }
}
