
solution {
    puzzle = "P108"
    name = "B GX"
    arm(ARM1) {
        number = 1
        position = -5 to 0
        rotation = -2
        size = 2
    }
    glyph(BONDER) {
        position = -3 to 0
        rotation = -2
    }
    glyph(UNBONDER) {
        position = -7 to 2
        rotation = -2
    }
    glyph(PROJECTION) {
        position = -4 to -2
        rotation = 4
    }
    glyph(ANIMISMUS) {
        position = -3 to -2
        rotation = 5
    }
    glyph(DISPOSAL) {
        position = -5 to 2
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -4 to 3
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -8 to 1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -8 to 2
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -7 to 3
        rotation = 0
    }
    io(OUTPUT) {
        index = 0
        position = -1 to 0
        rotation = 3
    }
    io(INPUT) {
        index = 0
        position = -6 to 1
        rotation = 28
    }
    io(INPUT) {
        index = 1
        position = -7 to 0
        rotation = 5
    }
    io(INPUT) {
        index = 2
        position = -5 to -2
        rotation = 0
    }
    track {
        position = -3 to 0
        positions = listOf(-2 to 0, -1 to 0, -1 to -1, -2 to -1)
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                grab()
                forward()
                forward()
                drop()
                back()
                rotateClockwise()
                back()
                grab()
                rotateClockwise()
                forward()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                forward()
                forward()
                grab()
                forward()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                forward()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                forward()
                forward()
                grab()
                forward()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                forward()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                forward()
                forward()
                grab()
                forward()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                forward()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                forward()
                grab()
                back()
                rotateCounterClockwise()
                back()
                back()
                rotateCounterClockwise()
                forward()
                pivotClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                back()
                rotateCounterClockwise()
                forward()
                forward()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                forward()
                grab()
                forward()
                rotateClockwise()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                grab()
                back()
                back()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                back()
                back()
                drop()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                forward()
                rotateClockwise()
                back()
                drop()
                back()
                rotateCounterClockwise()
                grab()
                back()
                back()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                forward()
                grab()
                back()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                back()
                grab()
                rotateClockwise()
                forward()
                drop()
                rotateClockwise()
                back()
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                forward()
                rotateClockwise()
                rotateClockwise()
                pivotCounterClockwise()
                back()
                drop()
                forward()
                forward()
                grab()
                back()
                rotateCounterClockwise()
                pivotClockwise()
                back()
                pivotCounterClockwise()
                pivotCounterClockwise()
                rotateClockwise()
                pivotCounterClockwise()
                forward()
                forward()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                pivotClockwise()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                drop()
                forward()
                forward()
                grab()
                back()
                pivotCounterClockwise()
                forward()
                drop()
                back()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                back()
                rotateCounterClockwise()
                drop()
                forward()
                grab()
                pivotClockwise()
                forward()
                drop()
                back()
                grab()
                forward()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                forward()
                grab()
                forward()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                back()
                back()
                drop()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                back()
                grab()
                back()
                back()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                forward()
                grab()
                back()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                back()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                forward()
                rotateClockwise()
                rotateClockwise()
                back()
                pivotCounterClockwise()
                drop()
                forward()
                forward()
                grab()
                back()
                drop()
                forward()
                grab()
                back()
                back()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                forward()
                grab()
                back()
                pivotCounterClockwise()
                back()
                drop()
                forward()
                forward()
                grab()
                back()
                back()
                drop()
                forward()
                forward()
                rotateClockwise()
                grab()
                forward()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                grab()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                rotateClockwise()
                back()
                drop()
                back()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                forward()
                forward()
                grab()
                forward()
                rotateClockwise()
                forward()
                drop()
                forward()
                rotateCounterClockwise()
                grab()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                forward()
                rotateClockwise()
                drop()
                forward()
                grab()
                back()
                rotateCounterClockwise()
                back()
                rotateCounterClockwise()
                forward()
                drop()
                forward()
                grab()
                forward()
                forward()
                rotateClockwise()
                forward()
                drop()
                rotateClockwise()
                back()
                grab()
                rotateCounterClockwise()
                rotateClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                forward()
                rotateClockwise()
                back()
                rotateClockwise()
                forward()
                drop()
                rotateClockwise()
                back()
                grab()
                rotateCounterClockwise()
                rotateClockwise()
                forward()
                pivotClockwise()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                forward()
                grab()
                back()
                drop()
                forward()
                grab()
                back()
                drop()
                back()
                back()
                grab()
                back()
                back()
                drop()
                rotateClockwise()
                back()
                grab()
                pivotCounterClockwise()
                rotateCounterClockwise()
                back()
                drop()
                rotateCounterClockwise()
                forward()
                forward()
                grab()
                back()
                back()
                drop()
                rotateClockwise()
                forward()
                grab()
                back()
                drop()
                forward()
                forward()
                reset()
            }
        }
        )
    }
}
