
solution {
    puzzle = "w2450508212"
    name = "B ACX"
    arm(PISTON) {
        number = 1
        position = 1 to -1
        rotation = -1
        size = 1
    }
    arm(PISTON) {
        number = 2
        position = 1 to -4
        rotation = 1
        size = 2
    }
    glyph(TRIPLEX_BONDER) {
        position = 0 to -3
        rotation = 0
    }
    glyph(UNBONDER) {
        position = 0 to -1
        rotation = 5
    }
    glyph(CALCIFICATION) {
        position = 0 to -4
        rotation = 0
    }
    glyph(DUPLICATION) {
        position = -2 to -2
        rotation = 25
    }
    io(INPUT) {
        index = 0
        position = 2 to -3
        rotation = 22
    }
    io(OUTPUT) {
        index = 0
        position = -1 to -2
        rotation = 10
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                pivotClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                wait(2)
                grab()
                pivotClockwise()
                drop()
                rotateClockwise()
                grab()
                pivotClockwise()
                extend()
                pivotCounterClockwise()
                drop()
                retract()
                rotateClockwise()
                grab()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                retract()
                wait(2)
                extend()
                drop()
                rotateClockwise()
                grab()
                extend()
                reset()
                wait(9)
                grab()
                pivotClockwise()
                drop()
                rotateClockwise()
                wait(5)
                grab()
                pivotClockwise()
                pivotClockwise()
                drop()
                rotateClockwise()
                grab()
                extend()
                extend()
                retract()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                wait(1)
                grab()
                rotateClockwise()
                extend()
                extend()
                retract()
                retract()
                rotateCounterClockwise()
                extend()
                drop()
                wait(1)
                grab()
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                extend()
                extend()
                drop()
                retract()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                drop()
                rotateClockwise()
                grab()
                pivotClockwise()
                pivotClockwise()
                drop()
                rotateClockwise()
                grab()
                extend()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                retract()
                wait(12)
                extend()
                pivotClockwise()
                pivotCounterClockwise()
                reset()
            }
        }
        , 
        {
            sequence(2) {
                wait(2)
                grab()
                pivotClockwise()
                retract()
                rotateCounterClockwise()
                extend()
                pivotClockwise()
                pivotClockwise()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                pivotClockwise()
                retract()
                drop()
                rotateClockwise()
                grab()
                pivotClockwise()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                extend()
                retract()
                pivotCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                wait(2)
                pivotCounterClockwise()
                pivotClockwise()
                drop()
                extend()
                grab()
                retract()
                drop()
                rotateClockwise()
                grab()
                pivotClockwise()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                extend()
                drop()
                extend()
                wait(1)
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                rotateCounterClockwise()
                extend()
                wait(1)
                retract()
                rotateClockwise()
                pivotClockwise()
                drop()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                pivotCounterClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                rotateClockwise()
                rotateCounterClockwise()
                drop()
                wait(1)
                grab()
                pivotCounterClockwise()
                extend()
                reset()
            }
        }
        )
    }
}
