
solution {
    puzzle = "w2450508212"
    name = "B AG 3T"
    arm(PISTON) {
        number = 1
        position = -2 to 0
        rotation = 0
        size = 1
    }
    glyph(TRIPLEX_BONDER) {
        position = -3 to 1
        rotation = 0
    }
    glyph(UNBONDER) {
        position = -2 to 3
        rotation = 4
    }
    glyph(CALCIFICATION) {
        position = -3 to 3
        rotation = 0
    }
    glyph(DUPLICATION) {
        position = -5 to 2
        rotation = 25
    }
    glyph(EQUILIBRIUM) {
        position = -3 to 0
        rotation = 0
    }
    io(INPUT) {
        index = 0
        position = -1 to 1
        rotation = 25
    }
    io(OUTPUT) {
        index = 0
        position = -4 to 3
        rotation = 13
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                extend()
                pivotClockwise()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                retract()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                reset()
                grab()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                pivotClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                retract()
                drop()
                rotateClockwise()
                extend()
                grab()
                retract()
                pivotClockwise()
                pivotCounterClockwise()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                drop()
                extend()
                extend()
                grab()
                retract()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                retract()
                grab()
                extend()
                retract()
                pivotCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                reset()
                grab()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                extend()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                pivotClockwise()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                retract()
                drop()
                rotateClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                drop()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                rotateClockwise()
                extend()
                drop()
                retract()
                retract()
                grab()
                extend()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                retract()
                grab()
                extend()
                retract()
                rotateClockwise()
                pivotClockwise()
                pivotClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                pivotCounterClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                rotateClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                retract()
                pivotClockwise()
                pivotCounterClockwise()
                drop()
                extend()
                extend()
                grab()
                retract()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                retract()
                grab()
                pivotCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                reset()
                grab()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                pivotClockwise()
                pivotClockwise()
                retract()
                drop()
                extend()
                extend()
                grab()
                retract()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                extend()
                retract()
                rotateClockwise()
                pivotClockwise()
                pivotClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                pivotCounterClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                rotateClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                retract()
                pivotClockwise()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                extend()
                reset()
            }
        }
        )
    }
}
