
solution {
    puzzle = "P036"
    name = "B GX"
    arm(ARM1) {
        number = 1
        position = -1 to -3
        rotation = 2
        size = 2
    }
    glyph(PURIFICATION) {
        position = -1 to -1
        rotation = -3
    }
    glyph(EQUILIBRIUM) {
        position = -2 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -3 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -1 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -2 to -2
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 0 to -2
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 1 to -3
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 2 to -3
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 0 to -1
        rotation = 0
    }
    io(INPUT) {
        index = 0
        position = -3 to -1
        rotation = 0
    }
    io(OUTPUT) {
        index = 0
        position = 1 to -2
        rotation = 0
    }
    track {
        position = -1 to -3
        positions = listOf(0 to 0, 1 to 0, 2 to -1)
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                forward()
                grab()
                back()
                rotateClockwise()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                rotateClockwise()
                grab()
                back()
                drop()
                rotateCounterClockwise()
                forward()
                forward()
                grab()
                back()
                drop()
                forward()
                grab()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                forward()
                grab()
                back()
                rotateClockwise()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                rotateClockwise()
                grab()
                back()
                drop()
                rotateCounterClockwise()
                forward()
                forward()
                grab()
                back()
                drop()
                forward()
                grab()
                back()
                drop()
                forward()
                rotateClockwise()
                grab()
                back()
                back()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                grab()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                forward()
                grab()
                back()
                rotateClockwise()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                rotateClockwise()
                grab()
                back()
                drop()
                rotateCounterClockwise()
                forward()
                forward()
                grab()
                back()
                drop()
                forward()
                grab()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                forward()
                grab()
                back()
                rotateClockwise()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                rotateClockwise()
                grab()
                back()
                drop()
                rotateCounterClockwise()
                forward()
                forward()
                grab()
                back()
                drop()
                forward()
                grab()
                back()
                drop()
                forward()
                rotateClockwise()
                grab()
                back()
                back()
                drop()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                grab()
                back()
                drop()
                forward()
                grab()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                forward()
                drop()
                back()
                reset()
                wait(1)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                forward()
                grab()
                back()
                rotateClockwise()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                rotateClockwise()
                grab()
                back()
                drop()
                rotateCounterClockwise()
                forward()
                forward()
                grab()
                back()
                drop()
                forward()
                grab()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                forward()
                grab()
                back()
                rotateClockwise()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                rotateClockwise()
                grab()
                back()
                drop()
                rotateCounterClockwise()
                forward()
                forward()
                grab()
                back()
                drop()
                forward()
                grab()
                back()
                drop()
                forward()
                rotateClockwise()
                grab()
                back()
                back()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                grab()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                forward()
                grab()
                back()
                rotateClockwise()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                rotateClockwise()
                grab()
                back()
                drop()
                rotateCounterClockwise()
                forward()
                forward()
                grab()
                back()
                drop()
                forward()
                grab()
                rotateClockwise()
                reset()
                wait(3)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                forward()
                grab()
                back()
                rotateClockwise()
                reset()
                wait(2)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                rotateClockwise()
                grab()
                back()
                drop()
                rotateCounterClockwise()
                forward()
                forward()
                grab()
                back()
                drop()
                forward()
                grab()
                back()
                drop()
                forward()
                rotateClockwise()
                grab()
                back()
                back()
                drop()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                grab()
                back()
                drop()
                forward()
                grab()
                back()
                drop()
                back()
                rotateClockwise()
                rotateClockwise()
                forward()
                grab()
                back()
                rotateCounterClockwise()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                reset()
            }
        }
        )
    }
}
