
solution {
    puzzle = "w2450512626"
    name = "B AC"
    arm(PISTON) {
        number = 1
        position = 2 to -3
        rotation = 7
        size = 2
    }
    arm(PISTON) {
        number = 2
        position = -2 to -1
        rotation = -1
        size = 1
    }
    glyph(BONDER) {
        position = -1 to -3
        rotation = 2
    }
    glyph(UNBONDER) {
        position = 3 to -3
        rotation = 2
    }
    glyph(CALCIFICATION) {
        position = 0 to -4
        rotation = 0
    }
    glyph(ANIMISMUS) {
        position = 1 to -4
        rotation = 1
    }
    glyph(UNIFICATION) {
        position = 0 to -1
        rotation = 1
    }
    io(OUTPUT) {
        index = 0
        position = -3 to -3
        rotation = -13
    }
    io(OUTPUT) {
        index = 1
        position = -3 to -1
        rotation = 7
    }
    io(INPUT) {
        index = 1
        position = 2 to -1
        rotation = -1
    }
    io(INPUT) {
        index = 3
        position = 0 to -2
        rotation = -3
    }
    tape {
        parallel(
        {
            sequence(2) {
                wait(3)
                grab()
                extend()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                grab()
                retract()
                drop()
                rotateClockwise()
                wait(2)
                grab()
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                extend()
                extend()
                drop()
                retract()
                retract()
                grab()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                pivotClockwise()
                drop()
                extend()
                grab()
                pivotCounterClockwise()
                pivotCounterClockwise()
                retract()
                drop()
                rotateCounterClockwise()
                extend()
                wait(9)
                grab()
                extend()
                reset()
                wait(8)
                grab()
                pivotCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                extend()
                pivotCounterClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                retract()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                pivotClockwise()
                extend()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                extend()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                wait(3)
                grab()
                extend()
                drop()
                retract()
                wait(4)
                grab()
                retract()
                drop()
                extend()
                wait(4)
                grab()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                extend()
                pivotClockwise()
                pivotClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                retract()
                rotateClockwise()
                grab()
                pivotClockwise()
                drop()
                extend()
                grab()
                pivotCounterClockwise()
                pivotCounterClockwise()
                retract()
                drop()
                rotateCounterClockwise()
                extend()
                wait(7)
                grab()
                extend()
                drop()
                retract()
                retract()
                grab()
                pivotCounterClockwise()
                wait(6)
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                extend()
                pivotCounterClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                retract()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                pivotClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(1) {
                grab()
                retract()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                pivotClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                retract()
                pivotCounterClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                extend()
                grab()
                extend()
                drop()
                retract()
                retract()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                wait(18)
                extend()
                extend()
                pivotCounterClockwise()
                retract()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                reset()
                wait(1)
                grab()
                retract()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                reset()
                wait(2)
                grab()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                extend()
                retract()
                pivotCounterClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                extend()
                grab()
                extend()
                drop()
                retract()
                retract()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                wait(18)
                extend()
                extend()
                pivotCounterClockwise()
                retract()
                drop()
                retract()
                reset()
            }
        }
        )
    }
}
