
solution {
    puzzle = "P070"
    name = "STUPID 308"
    arm(ARM1) {
        number = 1
        position = -2 to -2
        rotation = 0
        size = 2
    }
    arm(ARM1) {
        number = 2
        position = 0 to -1
        rotation = -4
        size = 2
    }
    arm(ARM1) {
        number = 3
        position = -3 to 2
        rotation = -2
        size = 1
    }
    arm(ARM1) {
        number = 4
        position = 1 to -2
        rotation = 2
        size = 2
    }
    glyph(BONDER) {
        position = -1 to 1
        rotation = 0
    }
    glyph(CALCIFICATION) {
        position = 2 to 0
        rotation = 0
    }
    glyph(DISPERSION) {
        position = -2 to 0
        rotation = 2
    }
    io(OUTPUT) {
        index = 0
        position = 1 to 2
        rotation = -4
    }
    io(INPUT) {
        index = 0
        position = 0 to -2
        rotation = 0
    }
    track {
        position = 1 to -1
        positions = listOf(0 to 0, 0 to -1)
    }
    track {
        position = -2 to 2
        positions = listOf(0 to 0, -1 to 0)
    }
    tape {
        parallel(
        {
            sequence(4) {
                wait(3)
                grab()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                reset()
                wait(1)
                grab()
                wait(1)
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                reset()
                wait(2)
                grab()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                reset()
                wait(1)
                grab()
                wait(1)
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                reset()
                wait(2)
                grab()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                reset()
                wait(1)
                grab()
                wait(1)
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                reset()
                wait(2)
                grab()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                reset()
                wait(1)
                grab()
                wait(1)
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                reset()
                wait(2)
                grab()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                reset()
                wait(1)
                grab()
                wait(1)
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                reset()
                wait(2)
                grab()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                reset()
                wait(1)
                grab()
                wait(1)
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                reset()
            }
        }
        , 
        {
            sequence(2) {
                wait(3)
                grab()
                rotateClockwise()
                pivotClockwise()
                wait(2)
                pivotClockwise()
                pivotClockwise()
                rotateClockwise()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                pivotCounterClockwise()
                reset()
                wait(8)
                grab()
                rotateClockwise()
                pivotClockwise()
                wait(2)
                pivotClockwise()
                pivotClockwise()
                rotateClockwise()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                pivotCounterClockwise()
                reset()
                wait(8)
                grab()
                rotateClockwise()
                pivotClockwise()
                wait(2)
                pivotClockwise()
                pivotClockwise()
                rotateClockwise()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                pivotCounterClockwise()
                reset()
                wait(8)
                grab()
                rotateClockwise()
                pivotClockwise()
                wait(2)
                pivotClockwise()
                pivotClockwise()
                rotateClockwise()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                pivotCounterClockwise()
                reset()
                wait(8)
                grab()
                rotateClockwise()
                pivotClockwise()
                wait(2)
                pivotClockwise()
                pivotClockwise()
                rotateClockwise()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                pivotCounterClockwise()
                reset()
                wait(2)
                grab()
                rotateCounterClockwise()
                reset()
                wait(3)
                grab()
                rotateClockwise()
                pivotClockwise()
                wait(2)
                pivotClockwise()
                pivotClockwise()
                rotateClockwise()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                pivotCounterClockwise()
                reset()
            }
        }
        , 
        {
            sequence(3) {
                wait(5)
                grab()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                grab()
                back()
                drop()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                back()
                reset()
                wait(5)
                grab()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                grab()
                back()
                drop()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(6)
                grab()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                grab()
                back()
                drop()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                rotateClockwise()
                reset()
                wait(7)
                grab()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                grab()
                back()
                drop()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                reset()
                wait(8)
                grab()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                grab()
                back()
                drop()
                rotateClockwise()
                forward()
                grab()
                wait(1)
                rotateCounterClockwise()
                reset()
                wait(7)
                grab()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                grab()
                back()
                reset()
            }
        }
        , 
        {
            sequence(1) {
                grab()
                rotateCounterClockwise()
                reset()
                wait(4)
                repeat()
                wait(13)
                grab()
                rotateCounterClockwise()
                reset()
                wait(4)
                repeat()
                wait(13)
                grab()
                rotateCounterClockwise()
                reset()
                wait(4)
                repeat()
                wait(13)
                grab()
                rotateCounterClockwise()
                reset()
                wait(4)
                repeat()
                wait(13)
                grab()
                rotateCounterClockwise()
                reset()
                wait(4)
                repeat()
                wait(13)
                grab()
                rotateCounterClockwise()
                reset()
                wait(4)
                repeat()
            }
        }
        )
    }
}
