
solution {
    puzzle = "w2501727977"
    name = "B AA BROTHERMOJO"
    arm(PISTON) {
        number = 1
        position = 1 to -4
        rotation = -4
        size = 2
    }
    arm(PISTON) {
        number = 2
        position = 4 to -2
        rotation = -3
        size = 2
    }
    glyph(TRIPLEX_BONDER) {
        position = 3 to -2
        rotation = -3
    }
    glyph(UNBONDER) {
        position = 1 to -3
        rotation = -3
    }
    glyph(UNIFICATION) {
        position = 4 to -4
        rotation = -4
    }
    glyph(EQUILIBRIUM) {
        position = -2 to 1
        rotation = 0
    }
    io(OUTPUT) {
        index = 0
        position = 2 to -1
        rotation = -4
    }
    io(INPUT) {
        index = 0
        position = -1 to -1
        rotation = -5
    }
    io(OUTPUT) {
        index = 1
        position = 2 to 0
        rotation = 0
    }
    track {
        position = 1 to -4
        positions = listOf(0 to 0, 1 to 0)
    }
    track {
        position = 4 to -2
        positions = listOf(0 to 0, 0 to 1)
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                retract()
                forward()
                pivotCounterClockwise()
                rotateClockwise()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                retract()
                grab()
                rotateClockwise()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                retract()
                grab()
                rotateClockwise()
                rotateClockwise()
                extend()
                extend()
                drop()
                back()
                retract()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                forward()
                drop()
                rotateCounterClockwise()
                grab()
                back()
                forward()
                drop()
                back()
                rotateCounterClockwise()
                grab()
                forward()
                rotateClockwise()
                extend()
                drop()
                rotateCounterClockwise()
                back()
                grab()
                retract()
                forward()
                pivotCounterClockwise()
                rotateClockwise()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                retract()
                grab()
                rotateClockwise()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                retract()
                grab()
                rotateClockwise()
                rotateClockwise()
                extend()
                extend()
                drop()
                back()
                retract()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                forward()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                back()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                wait(2)
                grab()
                forward()
                rotateClockwise()
                extend()
                retract()
                pivotClockwise()
                extend()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                pivotCounterClockwise()
                drop()
                retract()
                grab()
                rotateClockwise()
                rotateClockwise()
                extend()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                retract()
                grab()
                rotateClockwise()
                rotateClockwise()
                extend()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                retract()
                grab()
                rotateClockwise()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                back()
                grab()
                pivotClockwise()
                wait(2)
                rotateClockwise()
                rotateClockwise()
                forward()
                drop()
                rotateCounterClockwise()
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                rotateClockwise()
                extend()
                drop()
                back()
                grab()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                retract()
                grab()
                rotateClockwise()
                forward()
                extend()
                pivotCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                drop()
                retract()
                rotateClockwise()
                wait(1)
                grab()
                extend()
                pivotCounterClockwise()
                extend()
                drop()
                back()
                retract()
                rotateCounterClockwise()
                grab()
                forward()
                drop()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                drop()
                wait(3)
                grab()
                pivotClockwise()
                drop()
                back()
                extend()
                grab()
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(2) {
                wait(6)
                grab()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                wait(4)
                grab()
                rotateCounterClockwise()
                retract()
                drop()
                rotateClockwise()
                extend()
                extend()
                wait(3)
                grab()
                forward()
                pivotCounterClockwise()
                back()
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                retract()
                forward()
                grab()
                back()
                drop()
                rotateCounterClockwise()
                wait(1)
                grab()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                retract()
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                extend()
                forward()
                wait(1)
                retract()
                wait(1)
                extend()
                drop()
                back()
                grab()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                wait(3)
                grab()
                rotateCounterClockwise()
                retract()
                drop()
                rotateClockwise()
                grab()
                forward()
                extend()
                drop()
                back()
                extend()
                grab()
                forward()
                pivotCounterClockwise()
                back()
                pivotCounterClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                wait(4)
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                extend()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                pivotClockwise()
                retract()
                pivotClockwise()
                retract()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                pivotClockwise()
                retract()
                extend()
                pivotCounterClockwise()
                drop()
                forward()
                grab()
                extend()
                drop()
                retract()
                back()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                retract()
                grab()
                pivotClockwise()
                rotateClockwise()
                extend()
                forward()
                drop()
                back()
                wait(12)
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                extend()
                grab()
                pivotCounterClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                wait(1)
                grab()
                rotateClockwise()
                wait(1)
                extend()
                wait(1)
                drop()
                retract()
                grab()
                pivotCounterClockwise()
                rotateCounterClockwise()
                pivotCounterClockwise()
                retract()
                pivotCounterClockwise()
                drop()
                rotateClockwise()
                forward()
                extend()
                extend()
                grab()
                pivotCounterClockwise()
                back()
                drop()
                retract()
                forward()
                grab()
                extend()
                pivotClockwise()
                retract()
                drop()
                retract()
                wait(2)
                grab()
                pivotClockwise()
                pivotClockwise()
                extend()
                drop()
                wait(1)
                grab()
                retract()
                pivotClockwise()
                extend()
                drop()
                wait(1)
                grab()
                retract()
                pivotClockwise()
                drop()
                extend()
                extend()
                grab()
                retract()
                back()
                rotateClockwise()
                reset()
            }
        }
        )
    }
}
