
solution {
    puzzle = "P029"
    name = "OVERLAP AG"
    arm(PISTON) {
        number = 1
        position = 1 to -2
        rotation = 0
        size = 3
    }
    glyph(BONDER) {
        position = -9 to 0
        rotation = -1
    }
    glyph(BONDER) {
        position = -7 to 0
        rotation = -1
    }
    glyph(BONDER) {
        position = -3 to -2
        rotation = 1
    }
    glyph(BONDER) {
        position = -2 to -1
        rotation = 2
    }
    glyph(BONDER) {
        position = -1 to -2
        rotation = 1
    }
    glyph(BONDER) {
        position = 0 to -1
        rotation = 2
    }
    glyph(BONDER) {
        position = 3 to -2
        rotation = 2
    }
    glyph(BONDER) {
        position = -7 to -2
        rotation = 1
    }
    glyph(BONDER) {
        position = -5 to -1
        rotation = -2
    }
    glyph(BONDER) {
        position = -5 to 0
        rotation = -1
    }
    glyph(BONDER) {
        position = 1 to 0
        rotation = -1
    }
    glyph(BONDER) {
        position = 1 to -1
        rotation = -2
    }
    glyph(CALCIFICATION) {
        position = 2 to 0
        rotation = 0
    }
    glyph(PROJECTION) {
        position = 2 to -2
        rotation = 0
    }
    io(INPUT) {
        index = 0
        position = 2 to 0
        rotation = 0
    }
    io(INFINITE) {
        index = 0
        position = -9 to -1
        rotation = 0
    }
    io(INPUT) {
        index = 1
        position = 4 to -2
        rotation = 0
    }
    io(INPUT) {
        index = 2
        position = 2 to -2
        rotation = 0
    }
    track {
        position = -5 to 0
        positions = listOf(8 to -2, 8 to -1, 7 to -1, 6 to -1, 6 to -2, 5 to -1, 4 to 0, 3 to 0, 2 to 0, 2 to -1, 2 to -2, 1 to -1, 0 to 0, -1 to 0, -2 to 0, -2 to -1, -2 to -2)
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                retract()
                retract()
                forward()
                rotateClockwise()
                forward()
                forward()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                grab()
                forward()
                forward()
                drop()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                forward()
                forward()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                drop()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                back()
                extend()
                extend()
                grab()
                retract()
                retract()
                forward()
                rotateClockwise()
                forward()
                forward()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                forward()
                forward()
                drop()
                back()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                grab()
                forward()
                forward()
                drop()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                forward()
                forward()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                forward()
                drop()
                extend()
                grab()
                pivotCounterClockwise()
                drop()
                retract()
                back()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                back()
                rotateCounterClockwise()
                back()
                back()
                grab()
                forward()
                forward()
                drop()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                forward()
                forward()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                back()
                extend()
                extend()
                grab()
                retract()
                retract()
                forward()
                rotateClockwise()
                forward()
                forward()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                pivotCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                extend()
                drop()
                retract()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                back()
                extend()
                extend()
                grab()
                retract()
                retract()
                forward()
                rotateClockwise()
                forward()
                forward()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                drop()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                back()
                rotateCounterClockwise()
                back()
                back()
                grab()
                forward()
                forward()
                drop()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                forward()
                forward()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                pivotCounterClockwise()
                forward()
                rotateCounterClockwise()
                drop()
                forward()
                rotateCounterClockwise()
                extend()
                grab()
                pivotCounterClockwise()
                drop()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                back()
                extend()
                extend()
                grab()
                retract()
                retract()
                forward()
                rotateClockwise()
                forward()
                forward()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                drop()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                back()
                rotateCounterClockwise()
                back()
                back()
                grab()
                forward()
                forward()
                drop()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                forward()
                forward()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                drop()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                back()
                extend()
                extend()
                grab()
                retract()
                retract()
                forward()
                rotateClockwise()
                forward()
                forward()
                forward()
                rotateClockwise()
                forward()
                drop()
                back()
                rotateCounterClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                back()
                rotateCounterClockwise()
                back()
                back()
                grab()
                forward()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                forward()
                drop()
                extend()
                grab()
                pivotCounterClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                back()
                back()
                back()
                rotateCounterClockwise()
                back()
                rotateCounterClockwise()
                back()
                back()
                grab()
                forward()
                forward()
                rotateCounterClockwise()
                forward()
                drop()
                back()
                rotateClockwise()
                rotateClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                pivotCounterClockwise()
                forward()
                rotateCounterClockwise()
                forward()
                extend()
                drop()
                retract()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                rotateClockwise()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                back()
                back()
                grab()
                forward()
                forward()
                rotateCounterClockwise()
                pivotCounterClockwise()
                forward()
                rotateCounterClockwise()
                drop()
                forward()
                rotateCounterClockwise()
                extend()
                grab()
                pivotCounterClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                back()
                rotateCounterClockwise()
                back()
                extend()
                extend()
                grab()
                retract()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                drop()
                back()
                rotateClockwise()
                back()
                back()
                grab()
                forward()
                forward()
                rotateCounterClockwise()
                drop()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                rotateClockwise()
                back()
                grab()
                forward()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                back()
                back()
                grab()
                extend()
                pivotCounterClockwise()
                drop()
                retract()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                drop()
                back()
                rotateClockwise()
                grab()
                extend()
                drop()
                retract()
                forward()
                grab()
                back()
                drop()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                forward()
                grab()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                wait(1)
                extend()
                rotateCounterClockwise()
                reset()
            }
        }
        )
    }
}
