
solution {
    puzzle = "w2450560971"
    name = "B AG ROLAMNI"
    arm(PISTON) {
        number = 1
        position = 4 to -1
        rotation = 3
        size = 3
    }
    glyph(UNBONDER) {
        position = 3 to -1
        rotation = 4
    }
    glyph(PROJECTION) {
        position = 3 to -3
        rotation = 12
    }
    glyph(PURIFICATION) {
        position = 1 to 0
        rotation = 5
    }
    io(INPUT) {
        index = 0
        position = 1 to -2
        rotation = 4
    }
    io(OUTPUT) {
        index = 0
        position = 2 to 1
        rotation = 0
    }
    io(OUTPUT) {
        index = 1
        position = 4 to -2
        rotation = 0
    }
    track {
        position = 3 to 0
        positions = listOf(0 to 0, 1 to -1)
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                retract()
                retract()
                rotateClockwise()
                back()
                drop()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                back()
                pivotCounterClockwise()
                rotateClockwise()
                forward()
                extend()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                back()
                grab()
                pivotClockwise()
                pivotClockwise()
                drop()
                retract()
                grab()
                forward()
                extend()
                drop()
                back()
                grab()
                pivotClockwise()
                drop()
                retract()
                grab()
                rotateClockwise()
                extend()
                drop()
                forward()
                grab()
                retract()
                pivotClockwise()
                back()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                pivotClockwise()
                extend()
                drop()
                retract()
                forward()
                grab()
                rotateClockwise()
                drop()
                retract()
                back()
                grab()
                extend()
                forward()
                drop()
                retract()
                rotateClockwise()
                back()
                grab()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                grab()
                extend()
                drop()
                retract()
                forward()
                grab()
                extend()
                drop()
                extend()
                grab()
                retract()
                drop()
                retract()
                back()
                grab()
                extend()
                drop()
                retract()
                grab()
                rotateCounterClockwise()
                forward()
                reset()
                wait(3)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                repeat()
                wait(95)
                grab()
                retract()
                retract()
                rotateClockwise()
                back()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                grab()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                grab()
                rotateClockwise()
                extend()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                forward()
                drop()
                retract()
                rotateClockwise()
                back()
                grab()
                forward()
                pivotClockwise()
                back()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                pivotClockwise()
                extend()
                drop()
                retract()
                forward()
                grab()
                retract()
                drop()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                back()
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                extend()
                reset()
            }
        }
        )
    }
}
