
solution {
    puzzle = "w2450560971"
    name = "B ACX ROALMNI"
    arm(PISTON) {
        number = 1
        position = -4 to 1
        rotation = 0
        size = 3
    }
    arm(PISTON) {
        number = 2
        position = -3 to 0
        rotation = 1
        size = 2
    }
    glyph(UNBONDER) {
        position = -3 to 2
        rotation = 4
    }
    glyph(PROJECTION) {
        position = -3 to 3
        rotation = 3
    }
    glyph(PURIFICATION) {
        position = -1 to 0
        rotation = 2
    }
    io(INPUT) {
        index = 0
        position = -1 to 2
        rotation = 1
    }
    io(OUTPUT) {
        index = 0
        position = -2 to -1
        rotation = 0
    }
    io(OUTPUT) {
        index = 1
        position = -4 to 2
        rotation = 0
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                retract()
                retract()
                wait(1)
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                extend()
                drop()
                rotateClockwise()
                grab()
                pivotClockwise()
                retract()
                wait(2)
                extend()
                extend()
                drop()
                retract()
                grab()
                pivotClockwise()
                wait(1)
                retract()
                rotateCounterClockwise()
                drop()
                extend()
                grab()
                wait(1)
                rotateClockwise()
                drop()
                extend()
                grab()
                retract()
                drop()
                retract()
                grab()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                extend()
                reset()
                wait(3)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                grab()
                retract()
                retract()
                wait(1)
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                grab()
                extend()
                extend()
                drop()
                retract()
                retract()
                wait(6)
                grab()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                extend()
                grab()
                rotateClockwise()
                drop()
                wait(3)
                retract()
                rotateCounterClockwise()
                grab()
                rotateCounterClockwise()
                reset()
                wait(4)
                grab()
                rotateCounterClockwise()
                reset()
            }
        }
        , 
        {
            sequence(2) {
                wait(3)
                grab()
                pivotClockwise()
                wait(3)
                pivotClockwise()
                drop()
                retract()
                grab()
                rotateClockwise()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                extend()
                pivotClockwise()
                retract()
                drop()
                retract()
                grab()
                rotateClockwise()
                wait(1)
                rotateCounterClockwise()
                drop()
                extend()
                grab()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                extend()
                drop()
                retract()
                grab()
                extend()
                drop()
                retract()
                grab()
                extend()
                drop()
                retract()
                grab()
                rotateClockwise()
                reset()
                wait(3)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                repeat()
                wait(48)
                grab()
                pivotClockwise()
                wait(3)
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                retract()
                grab()
                rotateClockwise()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                wait(3)
                pivotClockwise()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                reset()
            }
        }
        )
    }
}
