
solution {
    puzzle = "P099"
    name = "OA"
    arm(VAN_BERLOS_WHEEL) {
        number = 1
        position = 2 to 1
        rotation = 0
        size = 1
    }
    arm(PISTON) {
        number = 2
        position = 1 to -1
        rotation = 1
        size = 1
    }
    glyph(UNBONDER) {
        position = 0 to 1
        rotation = 1
    }
    glyph(UNBONDER) {
        position = 0 to 2
        rotation = 0
    }
    glyph(UNBONDER) {
        position = -1 to 1
        rotation = 0
    }
    glyph(UNBONDER) {
        position = 1 to 0
        rotation = -1
    }
    glyph(UNBONDER) {
        position = 0 to 1
        rotation = -1
    }
    glyph(DUPLICATION) {
        position = 3 to -1
        rotation = -3
    }
    glyph(DUPLICATION) {
        position = 2 to 0
        rotation = -3
    }
    glyph(DUPLICATION) {
        position = 2 to 1
        rotation = -3
    }
    glyph(PROJECTION) {
        position = -1 to 1
        rotation = 0
    }
    glyph(PROJECTION) {
        position = 0 to 1
        rotation = -1
    }
    glyph(PROJECTION) {
        position = 1 to 0
        rotation = 1
    }
    glyph(PROJECTION) {
        position = 0 to 1
        rotation = 0
    }
    glyph(PURIFICATION) {
        position = 0 to 1
        rotation = -1
    }
    glyph(UNIFICATION) {
        position = 1 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 2 to 2
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 3 to 1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 4 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 4 to -1
        rotation = 0
    }
    io(INPUT) {
        index = 0
        position = 0 to 1
        rotation = 1
    }
    io(OUTPUT) {
        index = 0
        position = 1 to 1
        rotation = 0
    }
    io(INPUT) {
        index = 1
        position = 1 to 0
        rotation = 3
    }
    io(OUTPUT) {
        index = 1
        position = 1 to 0
        rotation = 0
    }
    track {
        position = 2 to 1
        positions = listOf(0 to 0, 1 to -1)
    }
    track {
        position = 1 to -1
        positions = listOf(0 to 0, 0 to 1, 0 to 2, -1 to 3)
    }
    tape {
        parallel(
        {
            sequence(1) {
                forward()
                wait(12)
                rotateCounterClockwise()
                wait(25)
                rotateCounterClockwise()
                rotateCounterClockwise()
                wait(24)
                rotateCounterClockwise()
                wait(14)
                rotateCounterClockwise()
                rotateCounterClockwise()
                wait(27)
                rotateCounterClockwise()
                wait(42)
                rotateCounterClockwise()
                rotateCounterClockwise()
                wait(11)
                rotateCounterClockwise()
                wait(19)
                rotateCounterClockwise()
                rotateCounterClockwise()
                wait(32)
                rotateCounterClockwise()
                wait(31)
                rotateCounterClockwise()
                rotateCounterClockwise()
                wait(32)
                rotateCounterClockwise()
                wait(14)
                rotateCounterClockwise()
                rotateCounterClockwise()
                wait(29)
                rotateCounterClockwise()
                wait(31)
                rotateCounterClockwise()
                rotateCounterClockwise()
                wait(32)
                rotateCounterClockwise()
                wait(14)
                rotateCounterClockwise()
                rotateCounterClockwise()
                wait(13)
                rotateClockwise()
                wait(48)
                rotateCounterClockwise()
                rotateCounterClockwise()
                wait(16)
                rotateClockwise()
            }
        }
        , 
        {
            sequence(2) {
                grab()
                forward()
                rotateCounterClockwise()
                drop()
                forward()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                back()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                drop()
                forward()
                rotateCounterClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                rotateClockwise()
                back()
                grab()
                rotateClockwise()
                rotateClockwise()
                back()
                rotateClockwise()
                rotateCounterClockwise()
                drop()
                forward()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                drop()
                back()
                rotateClockwise()
                grab()
                back()
                drop()
                forward()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                forward()
                rotateClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                back()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                rotateCounterClockwise()
                rotateClockwise()
                drop()
                forward()
                rotateCounterClockwise()
                grab()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                drop()
                back()
                rotateClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                rotateClockwise()
                rotateClockwise()
                grab()
                back()
                rotateClockwise()
                rotateCounterClockwise()
                drop()
                forward()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                back()
                rotateClockwise()
                grab()
                back()
                drop()
                forward()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                forward()
                rotateClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                back()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                rotateCounterClockwise()
                drop()
                forward()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                back()
                rotateClockwise()
                grab()
                back()
                drop()
                forward()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                forward()
                rotateClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                drop()
                back()
                rotateClockwise()
                grab()
                back()
                drop()
                forward()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                rotateCounterClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                forward()
                rotateClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                back()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                rotateCounterClockwise()
                drop()
                forward()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                back()
                rotateClockwise()
                grab()
                back()
                drop()
                forward()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                back()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                forward()
                rotateClockwise()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                drop()
                back()
                rotateClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                back()
                drop()
                rotateClockwise()
                back()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                extend()
                extend()
                drop()
                retract()
                retract()
                forward()
                grab()
                rotateCounterClockwise()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                back()
                grab()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                drop()
                rotateClockwise()
                grab()
                rotateClockwise()
                back()
                back()
                drop()
                forward()
                grab()
                rotateCounterClockwise()
                drop()
                forward()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                drop()
                back()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                drop()
                rotateClockwise()
                back()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                back()
                back()
            }
        }
        )
    }
}
