
solution {
    puzzle = "w2450511665"
    name = "H3 HUETOBI"
    arm(ARM1) {
        number = 1
        position = 13 to 1
        rotation = 4
        size = 2
    }
    arm(ARM1) {
        number = 2
        position = 11 to 1
        rotation = 4
        size = 1
    }
    arm(PISTON) {
        number = 3
        position = 10 to 1
        rotation = 4
        size = 1
    }
    arm(PISTON) {
        number = 4
        position = 9 to 1
        rotation = 4
        size = 1
    }
    arm(ARM1) {
        number = 5
        position = 8 to 1
        rotation = 4
        size = 1
    }
    arm(PISTON) {
        number = 6
        position = 12 to 1
        rotation = 4
        size = 1
    }
    arm(PISTON) {
        number = 7
        position = -1 to -1
        rotation = 1
        size = 1
    }
    arm(ARM1) {
        number = 8
        position = -5 to 0
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 9
        position = -7 to 1
        rotation = 5
        size = 2
    }
    arm(PISTON) {
        number = 10
        position = -6 to 1
        rotation = 5
        size = 2
    }
    arm(PISTON) {
        number = 11
        position = 2 to 1
        rotation = 3
        size = 3
    }
    arm(PISTON) {
        number = 12
        position = 4 to 1
        rotation = 4
        size = 2
    }
    arm(PISTON) {
        number = 13
        position = 6 to 1
        rotation = 5
        size = 1
    }
    glyph(BONDER) {
        position = 8 to -1
        rotation = 0
    }
    glyph(BONDER) {
        position = 4 to 0
        rotation = 5
    }
    glyph(BONDER) {
        position = -6 to -1
        rotation = 0
    }
    glyph(BONDER) {
        position = 12 to 0
        rotation = 0
    }
    glyph(UNBONDER) {
        position = 8 to 0
        rotation = 0
    }
    glyph(UNBONDER) {
        position = -3 to -1
        rotation = 1
    }
    glyph(UNBONDER) {
        position = -4 to -1
        rotation = 1
    }
    glyph(UNBONDER) {
        position = 10 to -1
        rotation = 1
    }
    glyph(UNBONDER) {
        position = 11 to 0
        rotation = 5
    }
    glyph(CALCIFICATION) {
        position = 3 to -1
        rotation = 0
    }
    glyph(ANIMISMUS) {
        position = 6 to 0
        rotation = 5
    }
    glyph(EQUILIBRIUM) {
        position = -2 to 1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 11 to -1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 24 to -1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 23 to 0
        rotation = 0
    }
    io(OUTPUT) {
        index = 0
        position = 2 to 0
        rotation = 2
    }
    io(INPUT) {
        index = 0
        position = -2 to 0
        rotation = 3
    }
    track {
        position = -5 to 0
        positions = listOf(0 to 0, -1 to 0)
    }
    track {
        position = -5 to 1
        positions = listOf(0 to 0, -1 to 0, -2 to 0, -3 to 0, -4 to 0)
    }
    track {
        position = 0 to -1
        positions = listOf(-1 to 0, 0 to 0, 1 to 0, 1 to 1)
    }
    track {
        position = 0 to 1
        positions = listOf(2 to 0, 3 to 0, 4 to 0, 5 to -1, 5 to 0, 6 to 0, 7 to 0, 8 to 0, 9 to 0, 10 to 0, 11 to 0, 12 to 0, 13 to 0, 14 to 0, 15 to 0, 16 to 0)
    }
    tape {
        parallel(
        {
            sequence(13) {
                wait(21)
                back()
                grab()
                forward()
                forward()
                reset()
                wait(3)
                repeat()
                wait(7)
                repeat()
                wait(31)
                forward()
                rotateClockwise()
                rotateClockwise()
                grab()
                forward()
                forward()
                forward()
                pivotCounterClockwise()
                back()
                rotateCounterClockwise()
                back()
                back()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                back()
                retract()
                wait(1)
                forward()
                grab()
                extend()
                drop()
                back()
                retract()
                wait(2)
                forward()
                grab()
                extend()
                drop()
                back()
                retract()
                wait(2)
                forward()
                grab()
                extend()
                drop()
                back()
                retract()
                wait(3)
                forward()
                grab()
                extend()
                drop()
                back()
                retract()
                wait(1)
                forward()
                grab()
                extend()
                drop()
                back()
                retract()
                wait(2)
                forward()
                grab()
                extend()
                drop()
                back()
                retract()
                wait(2)
                forward()
                grab()
                extend()
                drop()
                back()
                retract()
                wait(2)
                forward()
                grab()
                extend()
                drop()
                back()
                retract()
                wait(2)
                forward()
                grab()
                extend()
                drop()
                back()
                retract()
                wait(2)
                forward()
                grab()
                extend()
                drop()
                back()
                retract()
                wait(4)
                reset()
                grab()
                extend()
                reset()
            }
        }
        , 
        {
            sequence(12) {
                wait(13)
                back()
                grab()
                retract()
                forward()
                forward()
                reset()
                wait(2)
                retract()
                rotateCounterClockwise()
                wait(38)
                forward()
                forward()
                rotateCounterClockwise()
                extend()
                extend()
                wait(8)
                back()
                wait(1)
                grab()
                retract()
                forward()
                rotateClockwise()
                drop()
                retract()
                back()
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                wait(3)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                wait(4)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                wait(4)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                wait(4)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                wait(4)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                wait(4)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                wait(4)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                wait(4)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                wait(4)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                wait(4)
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                wait(4)
                grab()
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(11) {
                wait(8)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                drop()
                back()
                rotateClockwise()
                extend()
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                grab()
                retract()
                rotateCounterClockwise()
                retract()
                pivotClockwise()
                forward()
                forward()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                back()
                back()
                extend()
                wait(1)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                drop()
                rotateClockwise()
                back()
                forward()
                wait(4)
                grab()
                back()
                drop()
                extend()
                wait(1)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                back()
                drop()
                forward()
                rotateClockwise()
                wait(3)
                grab()
                back()
                drop()
                extend()
                wait(1)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                back()
                drop()
                forward()
                rotateClockwise()
                wait(3)
                grab()
                back()
                drop()
                extend()
                wait(1)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                back()
                drop()
                forward()
                rotateClockwise()
                wait(3)
                grab()
                back()
                drop()
                extend()
                wait(1)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                back()
                drop()
                forward()
                rotateClockwise()
                wait(3)
                grab()
                back()
                drop()
                extend()
                wait(1)
                grab()
                retract()
                rotateCounterClockwise()
                forward()
                back()
                drop()
                forward()
                wait(5)
                reset()
            }
        }
        , 
        {
            sequence(9) {
                wait(5)
                back()
                grab()
                forward()
                forward()
                forward()
                reset()
                wait(2)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(16)
                repeat()
                wait(17)
                repeat()
                wait(16)
                repeat()
                wait(15)
                back()
                grab()
                forward()
                forward()
                wait(33)
                forward()
                reset()
                wait(2)
                back()
                grab()
                forward()
                forward()
                forward()
                reset()
            }
        }
        , 
        {
            sequence(7) {
                wait(5)
                grab()
                forward()
                forward()
                reset()
                wait(4)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(5)
                forward()
                grab()
                forward()
                drop()
                rotateClockwise()
                forward()
                extend()
                extend()
                wait(1)
                grab()
                retract()
                pivotClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                back()
                back()
                back()
                grab()
                forward()
                forward()
                drop()
                rotateClockwise()
                extend()
                forward()
                wait(1)
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                back()
                back()
                back()
                grab()
                forward()
                forward()
                drop()
                rotateClockwise()
                extend()
                forward()
                wait(1)
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                back()
                back()
                back()
                grab()
                forward()
                forward()
                drop()
                rotateClockwise()
                extend()
                forward()
                wait(1)
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                back()
                back()
                back()
                grab()
                forward()
                forward()
                drop()
                rotateClockwise()
                extend()
                forward()
                wait(1)
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                back()
                back()
                back()
                grab()
                forward()
                forward()
                drop()
                rotateClockwise()
                extend()
                forward()
                wait(1)
                grab()
                pivotClockwise()
                wait(5)
                retract()
                reset()
            }
        }
        , 
        {
            sequence(2) {
                drop()
                wait(3)
                drop()
                wait(1)
                drop()
                wait(5)
                drop()
                drop()
                wait(1)
                drop()
                drop()
                wait(1)
                drop()
                wait(3)
                drop()
                wait(1)
                drop()
                drop()
                wait(1)
                drop()
                drop()
                wait(3)
                drop()
                wait(1)
                drop()
                wait(1)
                drop()
                wait(5)
                back()
                wait(24)
                forward()
                grab()
                forward()
                wait(3)
                forward()
                drop()
                forward()
                wait(4)
                back()
                back()
                wait(3)
                grab()
                back()
                back()
                drop()
                forward()
                wait(3)
                grab()
                back()
                back()
                drop()
                forward()
                wait(1)
                forward()
                wait(1)
                grab()
                back()
                back()
                drop()
                forward()
                forward()
                wait(2)
                grab()
                back()
                back()
                drop()
                forward()
                forward()
                wait(2)
                grab()
                back()
                back()
                drop()
                forward()
                forward()
                wait(2)
                grab()
                back()
                back()
                drop()
                forward()
                forward()
                wait(2)
                grab()
                back()
                back()
                drop()
                forward()
                forward()
                wait(2)
                grab()
                back()
                back()
                drop()
                forward()
                forward()
                wait(2)
                grab()
                back()
                back()
                drop()
                forward()
                forward()
                wait(2)
                grab()
                back()
                back()
                reset()
            }
        }
        , 
        {
            sequence(3) {
                drop()
                drop()
                drop()
                drop()
                drop()
                wait(1)
                drop()
                wait(5)
                drop()
                wait(1)
                drop()
                wait(1)
                drop()
                wait(1)
                drop()
                wait(3)
                drop()
                wait(1)
                drop()
                wait(1)
                drop()
                wait(1)
                drop()
                wait(3)
                drop()
                wait(2)
                drop()
                wait(2)
                grab()
                rotateCounterClockwise()
                reset()
                wait(1)
                back()
                wait(24)
                forward()
                wait(1)
                forward()
                wait(2)
                grab()
                forward()
                drop()
                forward()
                wait(3)
                grab()
                back()
                back()
                drop()
                wait(1)
                extend()
                back()
                back()
                back()
                grab()
                forward()
                drop()
                forward()
                wait(2)
                back()
                back()
                grab()
                forward()
                drop()
                forward()
                wait(2)
                back()
                back()
                grab()
                forward()
                drop()
                forward()
                wait(2)
                back()
                back()
                grab()
                forward()
                drop()
                forward()
                wait(2)
                back()
                back()
                grab()
                forward()
                drop()
                forward()
                wait(2)
                back()
                back()
                grab()
                forward()
                drop()
                forward()
                wait(2)
                back()
                back()
                grab()
                forward()
                drop()
                forward()
                wait(2)
                back()
                back()
                grab()
                forward()
                drop()
                forward()
                wait(2)
                back()
                back()
                grab()
                forward()
                drop()
                forward()
                wait(2)
                back()
                back()
                grab()
                forward()
                drop()
                forward()
                reset()
            }
        }
        , 
        {
            sequence(4) {
                drop()
                wait(3)
                drop()
                wait(1)
                drop()
                wait(5)
                drop()
                wait(3)
                drop()
                wait(1)
                drop()
                wait(3)
                drop()
                wait(1)
                drop()
                wait(3)
                drop()
                wait(3)
                drop()
                wait(2)
                drop()
                wait(6)
                back()
                wait(24)
                forward()
                wait(1)
                forward()
                wait(3)
                forward()
                wait(1)
                forward()
                wait(2)
                back()
                grab()
                back()
                back()
                wait(4)
                back()
                back()
                extend()
                drop()
                forward()
                forward()
                retract()
                grab()
                back()
                back()
                extend()
                drop()
                forward()
                forward()
                retract()
                grab()
                back()
                back()
                extend()
                drop()
                forward()
                forward()
                retract()
                grab()
                back()
                back()
                extend()
                drop()
                forward()
                forward()
                retract()
                grab()
                back()
                back()
                extend()
                drop()
                forward()
                forward()
                retract()
                grab()
                back()
                back()
                extend()
                drop()
                forward()
                forward()
                retract()
                grab()
                back()
                back()
                extend()
                drop()
                forward()
                forward()
                retract()
                grab()
                back()
                back()
                extend()
                drop()
                forward()
                forward()
                retract()
                grab()
                back()
                back()
                extend()
                drop()
                forward()
                forward()
                retract()
                grab()
                back()
                back()
                extend()
                drop()
                forward()
                forward()
                retract()
                grab()
                back()
                back()
                extend()
                reset()
            }
        }
        , 
        {
            sequence(5) {
                drop()
                wait(3)
                drop()
                wait(1)
                drop()
                wait(5)
                drop()
                wait(3)
                drop()
                wait(2)
                drop()
                drop()
                drop()
                wait(2)
                drop()
                wait(3)
                drop()
                wait(2)
                drop()
                drop()
                wait(2)
                drop()
                wait(6)
                back()
                wait(24)
                forward()
                wait(1)
                forward()
                wait(3)
                forward()
                wait(1)
                forward()
                wait(2)
                back()
                back()
                grab()
                back()
                wait(4)
                back()
                back()
                wait(1)
                drop()
                forward()
                forward()
                wait(1)
                grab()
                back()
                back()
                wait(1)
                drop()
                forward()
                forward()
                wait(1)
                grab()
                back()
                back()
                wait(1)
                drop()
                forward()
                forward()
                wait(1)
                grab()
                back()
                back()
                wait(1)
                drop()
                forward()
                forward()
                wait(1)
                grab()
                back()
                back()
                wait(1)
                drop()
                forward()
                forward()
                wait(1)
                grab()
                back()
                back()
                wait(1)
                drop()
                forward()
                forward()
                wait(1)
                grab()
                back()
                back()
                wait(1)
                drop()
                forward()
                forward()
                wait(1)
                grab()
                back()
                back()
                wait(1)
                drop()
                forward()
                forward()
                wait(1)
                grab()
                back()
                back()
                wait(1)
                drop()
                forward()
                forward()
                wait(1)
                grab()
                back()
                back()
                wait(1)
                drop()
                forward()
                forward()
                wait(1)
                grab()
                back()
                back()
                drop()
                wait(2)
                reset()
            }
        }
        , 
        {
            sequence(8) {
                grab()
                forward()
                pivotCounterClockwise()
                pivotClockwise()
                back()
                reset()
                wait(2)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(12)
                repeat()
                wait(17)
                repeat()
                wait(16)
                repeat()
                wait(15)
                repeat()
                wait(15)
                repeat()
            }
        }
        , 
        {
            sequence(10) {
                wait(5)
                back()
                grab()
                forward()
                forward()
                reset()
                wait(3)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(7)
                repeat()
                wait(10)
                rotateCounterClockwise()
                back()
                grab()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                forward()
                forward()
                reset()
                wait(7)
                rotateCounterClockwise()
                back()
                grab()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                forward()
                forward()
                reset()
                wait(6)
                rotateCounterClockwise()
                back()
                grab()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                forward()
                forward()
                reset()
                wait(5)
                rotateCounterClockwise()
                back()
                grab()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                forward()
                forward()
                reset()
                wait(5)
                rotateCounterClockwise()
                back()
                grab()
                extend()
                drop()
                retract()
                rotateClockwise()
                wait(25)
                grab()
                forward()
                forward()
                reset()
            }
        }
        , 
        {
            sequence(1) {
                drop()
                wait(3)
                drop()
                wait(1)
                drop()
                wait(5)
                drop()
                wait(3)
                drop()
                wait(2)
                drop()
                drop()
                drop()
                wait(2)
                drop()
                wait(3)
                drop()
                wait(13)
                back()
                grab()
                forward()
                forward()
                reset()
                wait(4)
                grab()
                forward()
                forward()
                reset()
                wait(4)
                grab()
                forward()
                forward()
                reset()
                wait(2)
                back()
                grab()
                forward()
                forward()
                forward()
                drop()
                back()
                grab()
                forward()
                forward()
                drop()
                wait(4)
                back()
                back()
                grab()
                forward()
                drop()
                wait(86)
                reset()
                wait(1)
                grab()
                forward()
                forward()
                reset()
            }
        }
        , 
        {
            sequence(6) {
                wait(42)
                back()
                grab()
                rotateCounterClockwise()
                forward()
                reset()
                wait(1)
                repeat()
                wait(5)
                back()
                grab()
                rotateCounterClockwise()
                forward()
                drop()
                back()
                rotateClockwise()
                wait(4)
                grab()
                rotateCounterClockwise()
                forward()
                drop()
                forward()
                wait(3)
                forward()
                wait(1)
                forward()
                wait(4)
                back()
                back()
                wait(19)
                extend()
                grab()
                retract()
                reset()
            }
        }
        )
    }
}
