
solution {
    puzzle = "w2450511665"
    name = "27A 1433C"
    arm(PISTON) {
        number = 1
        position = 1 to -3
        rotation = 3
        size = 2
    }
    glyph(BONDER) {
        position = 1 to -1
        rotation = 3
    }
    glyph(UNBONDER) {
        position = -1 to -2
        rotation = -1
    }
    glyph(ANIMISMUS) {
        position = 3 to -3
        rotation = 2
    }
    glyph(DISPOSAL) {
        position = -2 to 1
        rotation = 0
    }
    io(OUTPUT) {
        index = 0
        position = -2 to -1
        rotation = 2
    }
    io(INPUT) {
        index = 0
        position = -3 to -2
        rotation = 6
    }
    track {
        position = 1 to -3
        positions = listOf(0 to 0, 0 to 1)
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                retract()
                pivotClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                forward()
                grab()
                back()
                rotateClockwise()
                forward()
                extend()
                extend()
                drop()
                rotateCounterClockwise()
                retract()
                grab()
                pivotClockwise()
                pivotClockwise()
                drop()
                back()
                retract()
                grab()
                rotateClockwise()
                rotateClockwise()
                forward()
                rotateClockwise()
                drop()
                rotateClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                extend()
                drop()
                rotateCounterClockwise()
                retract()
                grab()
                pivotClockwise()
                pivotClockwise()
                rotateClockwise()
                extend()
                drop()
                back()
                rotateCounterClockwise()
                retract()
                retract()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                drop()
                retract()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                extend()
                extend()
                reset()
                wait(3)
                grab()
                retract()
                pivotClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                forward()
                grab()
                back()
                rotateClockwise()
                forward()
                extend()
                extend()
                drop()
                rotateCounterClockwise()
                retract()
                grab()
                pivotClockwise()
                pivotClockwise()
                drop()
                back()
                retract()
                grab()
                rotateClockwise()
                rotateClockwise()
                forward()
                rotateClockwise()
                drop()
                rotateClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                extend()
                drop()
                rotateCounterClockwise()
                retract()
                grab()
                pivotClockwise()
                pivotClockwise()
                rotateClockwise()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                back()
                retract()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                drop()
                retract()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                forward()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                rotateClockwise()
                reset()
                wait(5)
                extend()
                grab()
                retract()
                forward()
                pivotClockwise()
                extend()
                drop()
                back()
                retract()
                retract()
                grab()
                rotateClockwise()
                forward()
                extend()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                drop()
                back()
                retract()
                retract()
                grab()
                rotateClockwise()
                forward()
                extend()
                extend()
                drop()
                rotateCounterClockwise()
                retract()
                grab()
                retract()
                pivotCounterClockwise()
                pivotCounterClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                back()
                extend()
                pivotClockwise()
                drop()
                forward()
                grab()
                retract()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateCounterClockwise()
                rotateClockwise()
                back()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                extend()
                extend()
                drop()
                forward()
                retract()
                grab()
                back()
                reset()
            }
        }
        )
    }
}
