
solution {
    puzzle = "w2450511665"
    name = "OVERLAP AG 6T"
    arm(PISTON) {
        number = 1
        position = -2 to 1
        rotation = -7
        size = 1
    }
    glyph(BONDER) {
        position = -2 to 0
        rotation = -4
    }
    glyph(BONDER) {
        position = -2 to 0
        rotation = -6
    }
    glyph(BONDER) {
        position = -3 to 1
        rotation = -5
    }
    glyph(UNBONDER) {
        position = -1 to 0
        rotation = -5
    }
    glyph(UNBONDER) {
        position = -2 to 2
        rotation = -7
    }
    glyph(UNBONDER) {
        position = -3 to 2
        rotation = -6
    }
    glyph(ANIMISMUS) {
        position = -2 to 1
        rotation = -13
    }
    glyph(DISPOSAL) {
        position = -2 to 1
        rotation = 0
    }
    io(OUTPUT) {
        index = 0
        position = -2 to 0
        rotation = -14
    }
    io(INPUT) {
        index = 0
        position = -1 to 1
        rotation = -9
    }
    track {
        position = -3 to 1
        positions = listOf(0 to 0, 1 to 0, 1 to 1)
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                back()
                rotateCounterClockwise()
                drop()
                forward()
                grab()
                back()
                pivotClockwise()
                pivotClockwise()
                forward()
                back()
                drop()
                rotateCounterClockwise()
                forward()
                grab()
                rotateClockwise()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                forward()
                rotateClockwise()
                rotateClockwise()
                grab()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                back()
                drop()
                forward()
                rotateClockwise()
                grab()
                back()
                rotateCounterClockwise()
                drop()
                forward()
                grab()
                back()
                pivotClockwise()
                pivotClockwise()
                forward()
                back()
                drop()
                rotateCounterClockwise()
                forward()
                grab()
                rotateClockwise()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                forward()
                grab()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                forward()
                rotateCounterClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                back()
                pivotClockwise()
                forward()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                extend()
                grab()
                retract()
                back()
                rotateClockwise()
                drop()
                forward()
                grab()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                back()
                rotateClockwise()
                pivotCounterClockwise()
                forward()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                extend()
                grab()
                pivotCounterClockwise()
                back()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                reset()
                repeat()
                wait(154)
                repeat()
                wait(154)
                repeat()
                wait(154)
                repeat()
                wait(154)
                grab()
                back()
                rotateCounterClockwise()
                drop()
                forward()
                grab()
                back()
                pivotClockwise()
                pivotClockwise()
                forward()
                back()
                drop()
                rotateCounterClockwise()
                forward()
                grab()
                rotateClockwise()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                forward()
                rotateClockwise()
                rotateClockwise()
                grab()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                back()
                drop()
                forward()
                rotateClockwise()
                grab()
                back()
                rotateCounterClockwise()
                drop()
                forward()
                grab()
                back()
                pivotClockwise()
                pivotClockwise()
                forward()
                back()
                drop()
                rotateCounterClockwise()
                forward()
                grab()
                rotateClockwise()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                forward()
                grab()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                drop()
                forward()
                rotateCounterClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                back()
                pivotClockwise()
                forward()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                back()
                drop()
                forward()
                extend()
                grab()
                retract()
                back()
                rotateClockwise()
                drop()
                forward()
                grab()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                back()
                rotateClockwise()
                pivotCounterClockwise()
                forward()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                extend()
                grab()
                pivotCounterClockwise()
                back()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                reset()
            }
        }
        )
    }
}
