
solution {
    puzzle = "w2450511665"
    name = "A"
    arm(PISTON) {
        number = 1
        position = 3 to -3
        rotation = 2
        size = 2
    }
    glyph(BONDER) {
        position = 4 to -4
        rotation = 1
    }
    glyph(UNBONDER) {
        position = 2 to -2
        rotation = -3
    }
    glyph(ANIMISMUS) {
        position = 3 to -5
        rotation = 1
    }
    glyph(DISPOSAL) {
        position = 2 to 0
        rotation = 0
    }
    io(INPUT) {
        index = 0
        position = 0 to -1
        rotation = -7
    }
    io(OUTPUT) {
        index = 0
        position = 4 to -2
        rotation = -27
    }
    track {
        position = 3 to -4
        positions = listOf(0 to 1, -1 to 1)
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                retract()
                rotateClockwise()
                forward()
                extend()
                extend()
                drop()
                retract()
                retract()
                rotateCounterClockwise()
                grab()
                back()
                pivotClockwise()
                extend()
                drop()
                retract()
                forward()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                back()
                extend()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                extend()
                extend()
                drop()
                retract()
                back()
                rotateCounterClockwise()
                grab()
                retract()
                pivotClockwise()
                forward()
                drop()
                rotateClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                drop()
                extend()
                grab()
                retract()
                back()
                drop()
                forward()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                drop()
                retract()
                retract()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                extend()
                extend()
                drop()
                retract()
                back()
                rotateCounterClockwise()
                grab()
                retract()
                rotateClockwise()
                forward()
                extend()
                extend()
                drop()
                retract()
                retract()
                rotateCounterClockwise()
                grab()
                back()
                pivotClockwise()
                extend()
                drop()
                retract()
                forward()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                back()
                extend()
                drop()
                retract()
                rotateClockwise()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                extend()
                extend()
                drop()
                retract()
                back()
                rotateCounterClockwise()
                grab()
                retract()
                pivotClockwise()
                forward()
                drop()
                rotateClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                extend()
                extend()
                drop()
                retract()
                retract()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                extend()
                extend()
                drop()
                retract()
                back()
                rotateCounterClockwise()
                grab()
                retract()
                rotateClockwise()
                forward()
                extend()
                extend()
                drop()
                retract()
                retract()
                rotateCounterClockwise()
                grab()
                back()
                pivotClockwise()
                rotateClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                rotateClockwise()
                rotateCounterClockwise()
                extend()
                pivotClockwise()
                pivotClockwise()
                retract()
                drop()
                forward()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                pivotClockwise()
                drop()
                rotateClockwise()
                grab()
                pivotClockwise()
                back()
                drop()
                forward()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                pivotCounterClockwise()
                retract()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                back()
                forward()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                back()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                forward()
                grab()
                pivotCounterClockwise()
                drop()
                back()
                rotateCounterClockwise()
                grab()
                retract()
                drop()
                rotateClockwise()
                forward()
                grab()
                back()
                drop()
                forward()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                rotateClockwise()
                extend()
                extend()
                drop()
                retract()
                back()
                reset()
            }
        }
        )
    }
}
