
solution {
    puzzle = "P041"
    name = "B GA"
    arm(VAN_BERLOS_WHEEL) {
        number = 1
        position = -1 to -4
        rotation = 3
        size = 1
    }
    arm(ARM1) {
        number = 2
        position = 3 to -4
        rotation = 4
        size = 2
    }
    glyph(BONDER) {
        position = 2 to -3
        rotation = 0
    }
    glyph(DUPLICATION) {
        position = -1 to -3
        rotation = 0
    }
    glyph(ANIMISMUS) {
        position = 4 to -4
        rotation = 18
    }
    glyph(DISPOSAL) {
        position = 1 to -5
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -1 to -1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 4 to -2
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 1 to -2
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 2 to -1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = 5 to -3
        rotation = 0
    }
    io(OUTPUT) {
        index = 0
        position = 0 to -1
        rotation = -1
    }
    io(INPUT) {
        index = 1
        position = 3 to -6
        rotation = 0
    }
    track {
        position = 1 to -3
        positions = listOf(2 to -2, 1 to -1, 2 to -1, 3 to -2)
    }
    tape {
        parallel(
        {
            sequence(1) {
                wait(327)
                rotateClockwise()
                wait(102)
                reset()
            }
        }
        , 
        {
            sequence(2) {
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                back()
                drop()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                forward()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                back()
                drop()
                back()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                back()
                drop()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                forward()
                grab()
                back()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                forward()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                back()
                back()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                back()
                drop()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                forward()
                grab()
                back()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                forward()
                drop()
                rotateClockwise()
                back()
                grab()
                pivotClockwise()
                pivotClockwise()
                drop()
                forward()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                rotateCounterClockwise()
                forward()
                drop()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                forward()
                rotateClockwise()
                rotateClockwise()
                back()
                back()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                grab()
                rotateClockwise()
                forward()
                rotateClockwise()
                rotateClockwise()
                back()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                forward()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                back()
                back()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                forward()
                rotateClockwise()
                rotateClockwise()
                back()
                back()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                grab()
                rotateClockwise()
                forward()
                rotateClockwise()
                rotateClockwise()
                back()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                forward()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                drop()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                forward()
                forward()
                grab()
                forward()
                back()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                forward()
                rotateClockwise()
                rotateClockwise()
                forward()
                rotateClockwise()
                forward()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                grab()
                rotateClockwise()
                forward()
                rotateClockwise()
                rotateClockwise()
                back()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                forward()
                grab()
                rotateCounterClockwise()
                rotateCounterClockwise()
                forward()
                drop()
                rotateClockwise()
                forward()
                forward()
                grab()
                pivotClockwise()
                pivotClockwise()
                pivotClockwise()
                forward()
                drop()
                forward()
                rotateClockwise()
                rotateClockwise()
                grab()
                rotateCounterClockwise()
                rotateClockwise()
                forward()
                forward()
                pivotClockwise()
                drop()
                back()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                back()
                pivotClockwise()
                pivotClockwise()
                back()
                rotateClockwise()
                drop()
                back()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                rotateClockwise()
                back()
                back()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                forward()
                rotateCounterClockwise()
                back()
                pivotCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                rotateClockwise()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                forward()
                forward()
                pivotCounterClockwise()
                pivotCounterClockwise()
                rotateClockwise()
                forward()
                forward()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                back()
                back()
                rotateClockwise()
                drop()
                forward()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                rotateClockwise()
                forward()
                rotateCounterClockwise()
                back()
                pivotCounterClockwise()
                forward()
                drop()
                back()
                grab()
                rotateClockwise()
                back()
                drop()
                forward()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                forward()
                rotateClockwise()
                forward()
                rotateClockwise()
                drop()
                forward()
                forward()
                grab()
                back()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                back()
                back()
                pivotClockwise()
                pivotClockwise()
                drop()
                back()
                grab()
                pivotClockwise()
                pivotCounterClockwise()
                drop()
                rotateClockwise()
                grab()
                pivotCounterClockwise()
                rotateCounterClockwise()
                drop()
                forward()
                grab()
                back()
                drop()
                forward()
                forward()
                grab()
                forward()
                drop()
                rotateClockwise()
                forward()
                forward()
                grab()
                back()
                rotateCounterClockwise()
                drop()
                forward()
                grab()
                pivotClockwise()
                back()
                drop()
                rotateClockwise()
                rotateClockwise()
                grab()
                back()
                pivotClockwise()
                drop()
                forward()
                grab()
                rotateCounterClockwise()
                forward()
                pivotClockwise()
                forward()
                pivotClockwise()
                drop()
                back()
                grab()
                forward()
                drop()
                rotateCounterClockwise()
                back()
                grab()
                pivotClockwise()
                back()
                rotateClockwise()
                drop()
                rotateCounterClockwise()
                back()
                grab()
                back()
                drop()
                back()
                back()
                grab()
                forward()
                back()
                drop()
                forward()
                rotateClockwise()
                grab()
                back()
                reset()
            }
        }
        )
    }
}
