
solution {
    puzzle = "w2450512021"
    name = "B ACX 6T"
    arm(PISTON) {
        number = 1
        position = -4 to 4
        rotation = -7
        size = 1
    }
    arm(PISTON) {
        number = 2
        position = 1 to 1
        rotation = -3
        size = 2
    }
    glyph(BONDER) {
        position = -2 to 2
        rotation = -6
    }
    glyph(UNBONDER) {
        position = -3 to 4
        rotation = -6
    }
    glyph(DUPLICATION) {
        position = -2 to 1
        rotation = -3
    }
    io(INPUT) {
        index = 0
        position = -3 to 3
        rotation = -11
    }
    io(OUTPUT) {
        index = 0
        position = -1 to 1
        rotation = -8
    }
    io(INPUT) {
        index = 1
        position = -4 to 2
        rotation = -8
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                pivotCounterClockwise()
                extend()
                drop()
                rotateClockwise()
                wait(2)
                grab()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                retract()
                pivotCounterClockwise()
                pivotCounterClockwise()
                rotateClockwise()
                drop()
                extend()
                grab()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                extend()
                pivotCounterClockwise()
                drop()
                retract()
                grab()
                pivotCounterClockwise()
                extend()
                retract()
                wait(2)
                extend()
                rotateCounterClockwise()
                pivotClockwise()
                drop()
                rotateClockwise()
                grab()
                pivotClockwise()
                pivotClockwise()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                retract()
                rotateClockwise()
                extend()
                drop()
                rotateClockwise()
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                pivotCounterClockwise()
                drop()
                extend()
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                drop()
                retract()
                rotateClockwise()
                grab()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                drop()
                retract()
                grab()
                extend()
                reset()
                wait(2)
                repeat()
                wait(83)
                repeat()
                wait(83)
                repeat()
                wait(83)
                repeat()
                wait(83)
                grab()
                pivotCounterClockwise()
                extend()
                drop()
                rotateClockwise()
                wait(2)
                grab()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                retract()
                pivotCounterClockwise()
                pivotCounterClockwise()
                rotateClockwise()
                drop()
                extend()
                grab()
                rotateCounterClockwise()
                extend()
                drop()
                retract()
                retract()
                rotateClockwise()
                grab()
                extend()
                pivotCounterClockwise()
                drop()
                retract()
                grab()
                pivotCounterClockwise()
                extend()
                retract()
                wait(2)
                extend()
                rotateCounterClockwise()
                pivotClockwise()
                drop()
                rotateClockwise()
                grab()
                pivotClockwise()
                pivotClockwise()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                retract()
                rotateClockwise()
                extend()
                drop()
                rotateClockwise()
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                pivotCounterClockwise()
                drop()
                extend()
                grab()
                rotateCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                drop()
                retract()
                rotateClockwise()
                grab()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                drop()
                retract()
                grab()
                extend()
                extend()
                reset()
            }
        }
        , 
        {
            sequence(2) {
                wait(3)
                grab()
                pivotCounterClockwise()
                drop()
                extend()
                grab()
                pivotCounterClockwise()
                retract()
                pivotCounterClockwise()
                drop()
                wait(9)
                grab()
                extend()
                pivotCounterClockwise()
                pivotCounterClockwise()
                wait(2)
                pivotClockwise()
                wait(3)
                pivotClockwise()
                pivotCounterClockwise()
                retract()
                pivotCounterClockwise()
                pivotCounterClockwise()
                rotateClockwise()
                reset()
                wait(4)
                grab()
                pivotCounterClockwise()
                retract()
                pivotClockwise()
                pivotClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                pivotCounterClockwise()
                extend()
                drop()
                retract()
                retract()
                wait(17)
                grab()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                retract()
                drop()
                rotateClockwise()
                extend()
                grab()
                retract()
                reset()
                wait(2)
                repeat()
                wait(83)
                repeat()
                wait(83)
                repeat()
                wait(83)
                repeat()
                wait(83)
                grab()
                pivotCounterClockwise()
                drop()
                extend()
                grab()
                pivotCounterClockwise()
                retract()
                pivotCounterClockwise()
                drop()
                wait(9)
                grab()
                extend()
                pivotCounterClockwise()
                pivotCounterClockwise()
                wait(2)
                pivotClockwise()
                wait(3)
                pivotClockwise()
                pivotCounterClockwise()
                retract()
                pivotCounterClockwise()
                pivotCounterClockwise()
                rotateClockwise()
                reset()
                wait(4)
                grab()
                pivotCounterClockwise()
                retract()
                pivotClockwise()
                pivotClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                pivotCounterClockwise()
                extend()
                drop()
                retract()
                retract()
                wait(17)
                grab()
                extend()
                drop()
                rotateCounterClockwise()
                grab()
                retract()
                reset()
            }
        }
        )
    }
}
