
solution {
    puzzle = "w2450512021"
    name = "19A"
    arm(PISTON) {
        number = 1
        position = -3 to 4
        rotation = -2
        size = 1
    }
    glyph(BONDER) {
        position = -2 to 2
        rotation = 0
    }
    glyph(CALCIFICATION) {
        position = -4 to 3
        rotation = 0
    }
    glyph(DUPLICATION) {
        position = -2 to 4
        rotation = -2
    }
    io(OUTPUT) {
        index = 0
        position = -1 to 1
        rotation = -2
    }
    io(INPUT) {
        index = 0
        position = -3 to 2
        rotation = -4
    }
    io(INPUT) {
        index = 1
        position = -4 to 2
        rotation = -4
    }
    track {
        position = -4 to 4
        positions = listOf(0 to 0, 1 to 0)
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                extend()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                drop()
                rotateClockwise()
                rotateClockwise()
                extend()
                grab()
                retract()
                drop()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                back()
                pivotCounterClockwise()
                drop()
                rotateClockwise()
                grab()
                pivotCounterClockwise()
                pivotCounterClockwise()
                pivotClockwise()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                forward()
                drop()
                rotateClockwise()
                extend()
                grab()
                back()
                pivotClockwise()
                extend()
                drop()
                retract()
                retract()
                grab()
                pivotCounterClockwise()
                pivotCounterClockwise()
                drop()
                forward()
                extend()
                extend()
                grab()
                back()
                drop()
                retract()
                retract()
                forward()
                grab()
                rotateCounterClockwise()
                pivotCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateClockwise()
                grab()
                rotateClockwise()
                rotateCounterClockwise()
                drop()
                extend()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                back()
                grab()
                pivotClockwise()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                pivotClockwise()
                drop()
                retract()
                grab()
                pivotClockwise()
                extend()
                drop()
                rotateClockwise()
                rotateClockwise()
                forward()
                extend()
                grab()
                pivotCounterClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                drop()
                retract()
                back()
                grab()
                pivotClockwise()
                drop()
                rotateClockwise()
                forward()
                extend()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                back()
                grab()
                forward()
                drop()
                rotateClockwise()
                grab()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                back()
                extend()
                pivotClockwise()
                drop()
                retract()
                forward()
                grab()
                back()
                drop()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                pivotClockwise()
                drop()
                retract()
                grab()
                pivotClockwise()
                extend()
                drop()
                rotateClockwise()
                rotateClockwise()
                grab()
                retract()
                rotateCounterClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                pivotCounterClockwise()
                drop()
                rotateClockwise()
                extend()
                grab()
                retract()
                drop()
                rotateClockwise()
                extend()
                grab()
                pivotClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                rotateCounterClockwise()
                grab()
                rotateClockwise()
                pivotCounterClockwise()
                pivotCounterClockwise()
                extend()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                pivotCounterClockwise()
                drop()
                rotateCounterClockwise()
                extend()
                grab()
                retract()
                pivotClockwise()
                pivotClockwise()
                drop()
                rotateCounterClockwise()
                grab()
                pivotClockwise()
                drop()
                retract()
                forward()
                rotateClockwise()
                grab()
                extend()
                drop()
                back()
                grab()
                pivotCounterClockwise()
                drop()
                retract()
                rotateCounterClockwise()
                grab()
                extend()
                drop()
                retract()
                rotateClockwise()
                grab()
                extend()
                extend()
                reset()
            }
        }
        )
    }
}
