
solution {
    puzzle = "P095"
    name = "H2 6T"
    arm(PISTON) {
        number = 1
        position = -8 to 1
        rotation = 0
        size = 2
    }
    arm(ARM1) {
        number = 2
        position = 0 to 1
        rotation = 3
        size = 3
    }
    arm(ARM1) {
        number = 3
        position = -2 to 1
        rotation = 3
        size = 3
    }
    arm(ARM1) {
        number = 4
        position = -2 to 0
        rotation = 3
        size = 3
    }
    arm(ARM1) {
        number = 5
        position = -1 to 0
        rotation = 3
        size = 3
    }
    arm(ARM1) {
        number = 6
        position = -9 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 7
        position = -10 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 8
        position = -11 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 9
        position = -12 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 10
        position = -13 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 11
        position = -14 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 12
        position = -15 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 13
        position = -16 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 14
        position = -17 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 15
        position = -18 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 16
        position = -19 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 17
        position = -20 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 18
        position = -21 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 19
        position = -22 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 20
        position = -23 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 21
        position = -24 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 22
        position = -25 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 23
        position = -26 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 24
        position = -27 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 25
        position = -28 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 26
        position = -29 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 27
        position = -30 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 28
        position = -31 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 29
        position = -32 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 30
        position = -33 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 31
        position = -34 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 32
        position = -35 to 1
        rotation = 0
        size = 3
    }
    arm(ARM1) {
        number = 33
        position = -36 to 1
        rotation = 0
        size = 3
    }
    glyph(UNBONDER) {
        position = -6 to 0
        rotation = 0
    }
    glyph(PROJECTION) {
        position = -4 to 0
        rotation = 1
    }
    glyph(EQUILIBRIUM) {
        position = -37 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -38 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -39 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -44 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -45 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -46 to 0
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -48 to 1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -49 to 1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -50 to 1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -41 to 1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -42 to 1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -43 to 1
        rotation = 0
    }
    glyph(EQUILIBRIUM) {
        position = -8 to 0
        rotation = 0
    }
    io(INPUT) {
        index = 0
        position = -5 to 1
        rotation = 3
    }
    io(OUTPUT) {
        index = 0
        position = -3 to 1
        rotation = 4
    }
    track {
        position = -2 to 1
        positions = listOf(0 to 0, 0 to -1, 1 to -1, 1 to 0)
    }
    track {
        position = -14 to 1
        positions = listOf(-22 to 0, -21 to 0, -20 to 0, -19 to 0, -18 to 0, -17 to 0, -16 to 0, -15 to 0, -14 to 0, -13 to 0, -12 to 0, -11 to 0, -10 to 0, -9 to 0, -8 to 0, -7 to 0, -6 to 0, -5 to 0, -4 to 0, -3 to 0, -2 to 0, -1 to 0, 0 to 0, 1 to 0, 2 to 0, 3 to 0, 4 to 0, 5 to 0, 5 to -1, 4 to -1, 3 to -1, 2 to -1, 1 to -1, 0 to -1, -1 to -1, -2 to -1, -3 to -1, -4 to -1, -5 to -1, -6 to -1, -7 to -1, -8 to -1, -9 to -1, -10 to -1, -11 to -1, -12 to -1, -13 to -1, -14 to -1, -15 to -1, -16 to -1, -17 to -1, -18 to -1, -19 to -1, -20 to -1, -21 to -1, -22 to -1, -23 to 0, -24 to 0, -25 to 0, -26 to 0, -26 to -1, -27 to -1, -28 to -1, -29 to -1, -30 to 0, -31 to 0, -32 to 0, -33 to 0, -33 to -1, -34 to -1, -35 to -1, -36 to -1, -37 to 0, -38 to 0, -39 to 0)
    }
    track {
        position = -8 to 1
        positions = listOf(0 to 0, 1 to -1, 1 to 0)
    }
    tape {
        parallel(
        {
            sequence(1) {
                grab()
                forward()
                extend()
                forward()
                drop()
                forward()
                retract()
                wait(5)
                grab()
                back()
                extend()
                drop()
                retract()
                forward()
                wait(7)
                grab()
                back()
                extend()
                drop()
                retract()
                forward()
                wait(7)
                grab()
                back()
                extend()
                drop()
                retract()
                forward()
                wait(7)
                grab()
                back()
                extend()
                drop()
                retract()
                forward()
                wait(7)
                grab()
                back()
                extend()
                drop()
                retract()
                retract()
                wait(3)
                grab()
                back()
                back()
                wait(4)
                rotateCounterClockwise()
                drop()
                rotateClockwise()
                forward()
                grab()
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(3) {
                wait(2)
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
            }
        }
        , 
        {
            sequence(4) {
                wait(2)
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
                wait(1)
                forward()
            }
        }
        , 
        {
            sequence(5) {
                wait(2)
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                wait(1)
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                wait(1)
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                wait(1)
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                wait(1)
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                wait(1)
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
                forward()
                forward()
                grab()
                forward()
                forward()
                drop()
            }
        }
        , 
        {
            sequence(11) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(3)
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(1)
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(1)
                forward()
                forward()
                wait(2)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(19)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(10) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(2)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(25)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(9) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(25)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(8) {
                wait(3)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(28)
                rotateCounterClockwise()
                reset()
            }
        }
        , 
        {
            sequence(7) {
                wait(3)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(1)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(28)
                rotateCounterClockwise()
                reset()
            }
        }
        , 
        {
            sequence(6) {
                wait(2)
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(2)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(28)
                rotateCounterClockwise()
                reset()
            }
        }
        , 
        {
            sequence(2) {
                wait(12)
                grab()
                pivotCounterClockwise()
                drop()
                wait(10)
                repeat()
                wait(12)
                repeat()
                wait(12)
                repeat()
                wait(12)
                repeat()
                wait(12)
                repeat()
            }
        }
        , 
        {
            sequence(12) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(1)
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(1)
                forward()
                forward()
                forward()
                wait(1)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(20)
                rotateCounterClockwise()
                reset()
            }
        }
        , 
        {
            sequence(13) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(1)
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(1)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(20)
                rotateCounterClockwise()
                reset()
            }
        }
        , 
        {
            sequence(14) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(1)
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(1)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(16)
                rotateCounterClockwise()
                reset()
            }
        }
        , 
        {
            sequence(15) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(1)
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(1)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(2)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(17)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(16) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(3)
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(11)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(17) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(10)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(18) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                wait(7)
                rotateCounterClockwise()
                reset()
            }
        }
        , 
        {
            sequence(19) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(6)
                rotateCounterClockwise()
                reset()
            }
        }
        , 
        {
            sequence(21) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(3)
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(5)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(22) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(5)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(23) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(5)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(24) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(5)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(25) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(5)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(26) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(3)
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(5)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(27) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(5)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(28) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(5)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(29) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(5)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(30) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(5)
                rotateClockwise()
                reset()
            }
        }
        , 
        {
            sequence(31) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(3)
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(5)
                rotateClockwise()
                wait(1)
                reset()
            }
        }
        , 
        {
            sequence(32) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                grab()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(5)
                rotateClockwise()
                wait(2)
                reset()
            }
        }
        , 
        {
            sequence(33) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                forward()
                forward()
                wait(5)
                rotateClockwise()
                wait(3)
                reset()
            }
        }
        , 
        {
            sequence(20) {
                wait(3)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(4)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                wait(1)
                forward()
                grab()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(3)
                forward()
                forward()
                forward()
                forward()
                forward()
                forward()
                wait(5)
                rotateCounterClockwise()
                reset()
            }
        }
        )
    }
}
